### ISSUE TITLE
Using email whisper component will make OliveHelps crash

### ISSUE THREAD

**Issue by hans-hsieh-asus** [open-olive/loop-development-kit#135]
Using email whisper component will make OliveHelps crash.
```javascript
await whisperService.create({
      label: 'Email',
      components: [
        {
          type: whisperService.WhisperComponentType.Markdown,
          body: 'This is a "email" component without box. ',
        },
        {
          type: whisperService.WhisperComponentType.Email,
          value: 'test@example.com',
          tooltip: 'a tooltip',
          onChange: (newValue) => console.info(`new email: ${newValue}`),
        },
      ],
      onClose: () => {},
    });
```
OliveHelps will crash after running the code above in a loop.
LDK version: 3.0.0-beta.1
OliveHelps version: 0.16.2

**Comment by cshields-oliveai** [comment]
@hans-hsieh-asus - Thank you for bringing these issues to our attention! Thanks for providing version information, this will help us track it down quickly.

We have opened a new LDK ticket to resolve: SIDE-2186.
We will provide updates in this issue as we work to get it resolved, and will provide a pull request link if any work touches the LDK for your reference.

**Comment by BrettMugglinOlive** [comment]
I think your Email component is missing a `label` property. If you add one to its configuration, does that solve the issue?

**Comment by hans-hsieh-asus** [comment]
Thank you. After adding the missing `label` property, it's working now.
