### ISSUE TITLE
"step" and "tooltip" have no effect for "numberInput" whisper component

### ISSUE THREAD

**Issue by hans-hsieh-asus** [open-olive/loop-development-kit#137]
When using the `numberInput` whisper component, it looks like the `step` and `tooltip` don't have effect. E.g. 
```javascript
await whisperService.create({
      label: 'Number input',
      components: [
        {
          type: whisperService.WhisperComponentType.Markdown,
          body: 'This is a "number input" component without box.',
        },
        {
          type: whisperService.WhisperComponentType.Number,
          label: 'range [0, 10], step 2',
          value: 0,
          min: 0,
          max: 10,
          step: 2,
          tooltip: 'a tooltip',
          onChange: (newValue) => console.log(`New number: ${newValue}`),
        },
      ],
      onClose: () => {},
    });
```
LDK version: 3.0.0-beta.1
OliveHelps version: 0.16.2

**Comment by cshields-oliveai** [comment]
We have opened a new LDK ticket to investigate and resolve: SIDE-2188.
As with other your other reported issues, we will provide updates in this issue as we work to get it resolved, and will provide a pull request link if any work touches the LDK for your reference.

**Comment by BrettMugglinOlive** [comment]
This issue should be addressed in the next release of Olive Helps!

**Comment by CandiceCLB** [comment]
This has been released!  If you are still experiencing this issue after updating to Olive Helps v 0.17.3, please reopen.
