### ISSUE TITLE
Provide a storage folder for loops

### ISSUE THREAD

**Issue by latman-oliveai** [open-olive/loop-development-kit#143]
It would be helpful to have a place on disk that we can always rely on to store files. Our use-case is indexing files that the current human user has on their desktop. We would want to persist that index somewhere, but in the world of the secure loops, we don't know where to store our files that the user shouldn't need to be aware of.

**Comment by cshields-oliveai** [comment]
@latman-oliveai Labeling this one as an enhancement.

I will bring it back to the team to figure out if this is currently in the roadmap.

**Comment by cshields-oliveai** [comment]
@latman-oliveai - Can you provide some more clarity around the use case for this one? We would like to better understand what the files stored in these folders would we used for from a Loop perspective.

**Comment by latman-oliveai** [comment]
So we have some giant excel files and we would like to index them and store the index in a more performant format to allow users to search it. For more advanced loops we may want to store an SQLite database file so we can remember recently used sections of the loop, or help tailor whispers by remembering if the user clicked a button to tell us they didn't find a given whisper helpful for the situation.

**Comment by cshields-oliveai** [comment]
@latman-oliveai - Thanks for the clarification. We have created a new internal task for this: SIDE-2227.

**Comment by cshields-oliveai** [comment]
@latman-oliveai - We have made another pass on Filesystem Aptitude design as a team, and have determined that with the addition of:

- Allow Loop to report Olive Helps operating system
- Expose common folder paths: user directory, user desktop, user downloads
- and using the loop install subdirectory as the relative path

All of the needs of this request will be met. Components of this work are currently in progress, and the rest should follow shortly.

Let us know if there is still a use case that these will not resolve by reporting it in a new issue and we can work together to enable the behavior you are looking for.
