### ISSUE TITLE
Expose common folder paths: user directory, user desktop, user downloads

### ISSUE THREAD

**Issue by latman-oliveai** [open-olive/loop-development-kit#144]
We want to save new files into the user's downloads folder. But, the directory location is operating system dependent, and the loop isn't aware of the running user to locate their user directory.

**Comment by cshields-oliveai** [comment]
Hello @latman-oliveai - Thanks for opening this issue.

In version [3.0.0-beta.1](https://github.com/open-olive/loop-development-kit/releases/tag/v3.0.0-beta.1) of the LDK, the Filesystem aptitude has a `join` function that can take filepath segments, and return a string representing a filepath that is aware of the users operating system.

[Here](https://open-olive.github.io/loop-development-kit/ldk/javascript/interfaces/filesystem.html#join) is the documentation for that function.

I believe this would solve your issue. Let us know.

**Comment by latman-oliveai** [comment]
I loved seeing that just a few minutes ago. But I don't actually know where the user directory is, what operating system the loop is running on, and who the logged-in user is, so it would be hard to build the paths to get to the current user's desktop.

**Comment by cshields-oliveai** [comment]
Got it - I will mark this as an enhancement.

We **do** need to ensure security for the end user, and reporting to the Loop some of those things may be a violation. This one will take some discussion. Let me get some input from the teams and figure out priority for you.

Thanks for expanding on this.

**Comment by cshields-oliveai** [comment]
@latman-oliveai - The team feels that this is a good idea, and would like to add it to the roadmap. We have created a new internal task for this: SIDE-2209. We will update this Github Issue when we complete the feature.

**Comment by latman-oliveai** [comment]
Great thanks!

**Comment by CandiceCLB** [comment]
Updating ticket number for tracking: HELPS-166

**Comment by BrettMugglinOlive** [comment]
I'm going to go ahead and close this thread. Please feel free to reopen if you feel that the problem still doesn't have an adequate workaround through using the System aptitude to determine OS, and change behavior based on that.
