### ISSUE TITLE
Detect changes to loop.js for local loops and auto restart the loop.

### ISSUE THREAD

**Issue by latman-oliveai** [open-olive/loop-development-kit#145]
We are currently creating symbolic links between our webpack build folder and the secure loops directory. It would be awesome if the helps application would auto restart the loop every time `webpack --watch` rebuilds the loop.

**Comment by cshields-oliveai** [comment]
@latman-oliveai Another label for enhancement here. Same goes, will get with the team to figure out priority for this.

Thanks!

**Comment by cshields-oliveai** [comment]
@latman-oliveai - We have created another new internal task for this one SIDE-2211. As always, we will update here when progress is made.

**Comment by CandiceCLB** [comment]
Updating ticket number- HELPS-328

**Comment by MaggieMaSS** [comment]
This feature has been done in November 2021.
