### ISSUE TITLE
Add support to update an existing whisper

### ISSUE THREAD

**Issue by hans-hsieh-asus** [open-olive/loop-development-kit#149]
Let's say I have several checkboxes in a whisper for different options, and the first checkbox's label is "select all". The behavior I want is when the user checks the first checkbox, all the other checkboxes will become checked.   
To achieve this behavior, we need to programmatically update a created whisper. 
As discussed [here](https://github.com/open-olive/loop-development-kit/discussions/140), it is currently not supported.  
I hope the support can be added to enhance the user experience.

**Comment by cshields-oliveai** [comment]
Thank you @hans-hsieh-asus. This is in the product backlog. Will update here when it makes it into a release.

**Comment by cshields-oliveai** [comment]
An update on this one - This is work in progress. For reference, our internal task for this is SIDE-2091.

**Comment by richseviora** [comment]
@hans-hsieh-asus this change has been released today in Olive Helps v18.10 and LDK version v3.0.0-beta.4!
