### ISSUE TITLE
Bold text style isn't supported in Markdown whisper component

### ISSUE THREAD

**Issue by hans-hsieh-asus** [open-olive/loop-development-kit#151]
If I use the following code, the text isn't in bold. 
```javascript
await whisper.create({
      label: 'test',
      onClose: () => {},
      components: [
        {
          type: whisper.WhisperComponentType.Markdown,
          body: '**Bold**',
        }
      ],
    });
```
However, it looks to be working for the body of a `Message`.
```javascript
await whisper.create({
      label: 'test',
      onClose: () => {},
      components: [
        {
          type: whisper.WhisperComponentType.Message,
          body: '**Bold**',
        }
      ],
    });
```

**Comment by cshields-oliveai** [comment]
Hello, @hans-hsieh-asus - I tested this out a few ways I think I see the difference. 

The bold style of content within a Message Whisper is different than the bold style for a Markdown Whisper.

This example - 
```typescript
whisper.create({
    label: 'Clipboard Text Whisper',
    onClose: () => {
      console.log("Closed Clipboard Text Whisper");
    },
    components: [
      {
        body: `Got Clipboard Text: ${incomingText}`,
        type: whisper.WhisperComponentType.Markdown,
      },
      {
        body: 'Markdown Whisper NOT bold **Markdown Whisper Bold**',
        type: whisper.WhisperComponentType.Markdown,
      },
      {
        type: whisper.WhisperComponentType.Message,
        body: 'Message Whisper NOT bold **Message Whisper Bold**',
      }
    ]
  });
```

Yields these results:
![Screen Shot 2021-05-05 at 4 04 09 PM](https://user-images.githubusercontent.com/81329854/117202198-8bbf6d00-adbb-11eb-88ff-9b93e7c22279.png)

The design of the Message Whisper and the Markdown Whisper do differ. The standard weight of the text it heavier with Message Whisper.

**Comment by hans-hsieh-asus** [comment]
Thanks. I see. the **bold** does take effect. It's just not that obvious for *Markdown* component.
