### ISSUE TITLE
Text styling and logo image

### ISSUE THREAD

**Issue by hans-hsieh-asus** [open-olive/loop-development-kit#152]
At the bottom left corner of a whisper, there's an Olive logo.
![image](https://user-images.githubusercontent.com/68371064/117117964-bfea5c00-adc2-11eb-965a-c336ae85a8ca.png)
Is it possible to change the icon?
Another question is that whether it is possible to change the foreground color of the text? (for components like *message* and *markdown*). It looks like the markdown component doesn't allow HTML syntax like
```html
<span style="color:blue">some *blue* text</span>.
```

**Comment by EddieAtOlive** [comment]
### Is it possible to change the icon?
You can choose what logo to show in the bottom left of the Whisper when you add your Loop and when you submit it to be published. However, the work to make it actually change what's in the Whisper has not been completed yet. If you've already set it to be your own logo, once that work is complete by the Olive Helps team, it will automatically start showing correctly. That work is scheduled for this sprint, so you can expect it within the next few weeks. For reference, we're tracking this task as SIDE-1371 internally.

### Is it possible to change the foreground color of the text?
No, it is not possible to change the colors of the text right now. At this stage of the product, we want to make sure we're delivering a very consistent visual experience across all the Loops a user might use. To get an overall feel for the visual experience, you can visit the [Olive Helps Design Kit](https://olive.page.link/olive-helps-design-kit).

**Comment by hans-hsieh-asus** [comment]
Thanks, I checked the design kit already. But some components look different from what I actually see for now.
For example, from the design kit, it looks like there're several kinds of buttons: primary, secondary, reversed, etc. But it looks like we are only able to create the *primary* button for now?
And for the icon, do you mean the bottom left one will become the *Loop Logo* we use?

**Comment by EddieAtOlive** [comment]
### design kit mismatch
Sorry about the current inconsistencies of the design kit vs what's actually available in the LDK today. We intend to keep adding features to match up with those styles and also incorporate that kit directly into the LDK docs to keep them in-sync.

### Loop Logo / Icon
I misspoke a little earlier when describing the current state of how the logo in the bottom left is set/shown. The Loop logo that you pick when creating your Loop is what will be shown in the top left corner. The logo that will show in the bottom left will be your organization logo (once the change mentioned above is release in the next few weeks). That logo can only be set by us at Olive for now. The feature to allow Authors to set their own organization logo is on our list, but that work hasn't been started yet. For now, we've set it to the logo shown in your website header. We'll work with you directly to make sure that's the right one before you submit your Loop for publishing.
