### ISSUE TITLE
Allow Loop to report Olive Helps operating system

### ISSUE THREAD

**Issue by cshields-oliveai** [open-olive/loop-development-kit#155]
Some Loop Authors have requested to allow a Loop to report which operating system it is currently executing under.

Some reasons include:
1. To provide operating system specific filesystem operations
2. To provide operating system specific keyboard listening logic

### Notes
Currently, the LDK _does_ include [filesystem.join(string[])](https://open-olive.github.io/loop-development-kit/ldk/javascript/interfaces/filesystem.html#join) that "joins an array of path elements into a single path, separating them with an OS specific Separator"

The LDK also supports `meta`, `metaLeft`, `metaRight` keys that will map operating system specific keys (cmd for Mac, windows key for Windows).

**Comment by CandiceCLB** [comment]
JIRA ticket SIDE-452

**Comment by CandiceCLB** [comment]
This has been done with the release of LDK v3.2.0. Closing.
