### ISSUE TITLE
`Filesystem.mkdir` fails due to read-only file system for local loop

### ISSUE THREAD

**Issue by kdouglass-oliveai** [open-olive/loop-development-kit#158]
```
ldk.filesystem.makeDir(`${__dirname}hello-world`, 54);
```

Error message
_Unhandled promise rejection GoError: mkdir helloworld: read-only file system_

**Comment by cshields-oliveai** [comment]
Hello @kdouglass-oliveai - Can you demonstrate how you are making the call to `filesystem.makeDir()`?

For reference, the interface for `makeDir` function ([LDK v3.0.0-beta.1](https://github.com/open-olive/loop-development-kit/releases/tag/v3.0.0-beta.1)) is as follows:

```typescript
/**
 * Makes a directory at the specified location.
 * @param destination - destination of where directory needs to be created at
 * @param writeMode - file mode and permission bits
 */
makeDir(destination: string, writeMode: WriteMode): Promise<void>;
```

**Comment by kdouglass-oliveai** [comment]
Updated original issue, but it appears to be a webpack issue since `__dirname` is just converted to `/`

**Comment by RusGraf** [comment]
Hello @kdouglass-oliveai, I have couple of thoughts in here. First of all you cant depend on node capabilities as I'm not sure how well will it transpile with the webpack. We have an enhancement request which may help users with supplying better paths: https://github.com/open-olive/loop-development-kit/issues/144. Also, please make sure to specify octal number as permission bits (ex. 0o755) so it will properly propagates through the system.

**Comment by kdouglass-oliveai** [comment]
ok, thanks for the response.

At this time is it even possible/reliable to use the filesystem without knowing an absolute path on a user's machine? If I try to create a a file in the current working directory using a relative URL it returns a `read-only file system` error. If I try to read a file with a relative URL a `no such file or directory` error message is returned. If I try both examples above with an absolute URL they work as expected.

`await filesystem.makeDir('./hello-world', 0o755);`
`{"level":"info","system":"authenticated application","system":"secureloops","loopID":"73893405-b802-4932-958c-7e1cd95faf08","console":"log","time":"2021-05-07T09:47:29-04:00","message":"GoError: mkdir ./hello-world: read-only file system"}`

`await filesystem.exists('./helloworld.txt');`
`await filesystem.readFile('./helloworld.txt');`
 `{"level":"info","system":"authenticated application","system":"secureloops","loopID":"73893405-b802-4932-958c-7e1cd95faf08","console":"log","time":"2021-05-07T09:46:14-04:00","message":"GoError: stat ./helloworld.txt: no such file or directory"}`

**Comment by cshields-oliveai** [comment]
@kdouglass-oliveai - You are correct, with the current release of the LDK, absolute paths are what you will need to work with.

We have a few other initiatives to streamline working with the filesystem however: https://github.com/open-olive/loop-development-kit/issues/144, https://github.com/open-olive/loop-development-kit/issues/143.

We also currently have the [filesystem.join()](https://open-olive.github.io/loop-development-kit/ldk/javascript/interfaces/filesystem.html#join) utility.

As always, if you are seeing opportunities for enhancements, we would be happy to discuss them further (via a new Github Issue) and get them prioritized in our roadmap!

I am going to close this one up for now - as I mentioned above, please feel free to open a new issue and tag as "enhancement" if you would like to see new functionality.
