### ISSUE TITLE
Document writeMode number in `filesystem.writeFile` or expose an enum WriteMode.Whatever = 54

### ISSUE THREAD

**Issue by latman-oliveai** [open-olive/loop-development-kit#160]
```
 const testEncodedString = await network.encode('Hi');
    await filesystem.writeFile(
      '/Users/michaellatman/Desktop/test.txt',
      testEncodedString,
      WriteOperation.overwrite,
      **????? What can go here?**
    );
```

**Comment by cshields-oliveai** [comment]
@latman-oliveai - Thank you for the suggestion here. I can bring this back to the team and figure out where something like this can fit on the roadmap.

For your reference, the Typescript `number` for `WriteMode` as part of the `filesystem.writeFile` interface:

`writeFile(params: WriteFileParams): Promise<void>;`

where:
```
interface WriteFileParams {
    ...
    writeMode: WriteMode;
}
```
and: `type WriteMode = number;`

is eventually converted into [FileMode](https://golang.org/pkg/os/#FileMode).

So the `WriteMode` values you are sending into `writeFile` can be represented as `0o755`, `0o777` etc...

**Comment by richseviora** [comment]
I think we also want to validate that the value provided is valid and provide a specific error message; anything >= `0o777` is probably not valid.

**Comment by cshields-oliveai** [comment]
@latman-oliveai We have created a new internal task to add extra documentation around `WriteMode`: SIDE-2229

**Comment by richseviora** [comment]
OK the documentation changes should now be live!
