### ISSUE TITLE
Full screen OCR Support

### ISSUE THREAD

**Issue by latman-oliveai** [open-olive/loop-development-kit#161]
We'd like to OCR the entire display such that we can extract patient numbers and other info from applications.

**Comment by CandiceCLB** [comment]
Hello @latman-oliveai ! We have an exploratory card on our backlog regarding this time. We will keep this thread updated with the latest status.

**Comment by CandiceCLB** [comment]
Updating ticket: HELPS-468

**Comment by CandiceCLB** [comment]
Updating ticket number: HELPS-1050

**Comment by BrettMugglinOlive** [comment]
OCR is now available with release 3.7.0
