### ISSUE TITLE
Behavior of keyboard hotkey

### ISSUE THREAD

**Issue by hans-hsieh-asus** [open-olive/loop-development-kit#163]
When trying out the `keyboard.listenHotkey()` in the javascript LDK, some behaviors look a little strange. I'm not sure if they are bugs or intended behaviors.
- On Mac, it looks like the `meta` key maps to `options` key on the keyboard, and `alt` key maps to the `cmd` key on the keyboard. Shouldn't they be reversed? I'm not that familiar with Mac. Maybe I'm wrong.
- When I press Ctrl + I, all the listeners for Ctrl + I, Ctrl + shift + I, Ctrl + meta + I, and Ctrl + Alt + I will be called. Is that the intended behavior? If so, how do I distinguish the user is pressing Ctrl + I instead of Ctrl + Alt + I?
- If I press Ctrl + I for a few seconds and release, the listener will be called with argument `pressed` being `true` for several times. But it is never called with `false`.

**Comment by hans-hsieh-asus** [comment]
Thank you for your reply. For the first one, because I don't have Mac, I asked my colleagues to test it for me. I'll confirm with her. :)

**Comment by cshields-oliveai** [comment]
Hello @hans-hsieh-asus - I have been investigating point #3:

`If I press Ctrl + I for a few seconds and release, the listener will be called with argument pressed being true for several times. But it is never called with false.`

I am not seeing the same behavior. In my testing, the callback for `keyboard.listenHotkey()` is only called a single time - on first press of the hotkey and not on held hotkeys.

Do you have any more information about your testing that can help us investigate this one? A few things that can help:

- Olive Helps version
- LDK version
- Operating system
- Code examples with your usage of `keyboard.listenHotkey()`

**Comment by hans-hsieh-asus** [comment]
> Hello @hans-hsieh-asus - I have been investigating point 3:
> 
> `If I press Ctrl + I for a few seconds and release, the listener will be called with argument pressed being true for several times. But it is never called with false.`
> 
> I am not seeing the same behavior. In my testing, the callback for `keyboard.listenHotkey()` is only called a single time - on first press of the hotkey and not on held hotkeys.
> 
> Do you have any more information about your testing that can help us investigate this one? A few things that can help:
> 
> * Olive Helps version
> * LDK version
> * Operating system
> * Code examples with your usage of `keyboard.listenHotkey()`

@cshields-oliveai 
Here's the code example:
```javascript
keyboard.listenHotkey({
  key: 'i',
  control: true,
}, (pressed) => {
  console.info(`======= received hot key. pressed: ${pressed}`);
});
console.info('======= registered hotkey');
```
What I see in the log:
```
{"level":"info","system":"authenticated application","system":"secureloops","loopID":"70fb422c-eb8c-4cd3-b1e7-1d3e7456d295","console":"info","time":"2021-05-14T09:33:19+08:00","message":"======= registered hotkey"}
{"level":"info","system":"authenticated application","system":"secureloops","loopID":"70fb422c-eb8c-4cd3-b1e7-1d3e7456d295","console":"info","time":"2021-05-14T09:33:23+08:00","message":"======= received hot key. pressed: true"}
{"level":"info","system":"authenticated application","system":"secureloops","loopID":"70fb422c-eb8c-4cd3-b1e7-1d3e7456d295","console":"info","time":"2021-05-14T09:33:23+08:00","message":"======= received hot key. pressed: true"}
{"level":"info","system":"authenticated application","system":"secureloops","loopID":"70fb422c-eb8c-4cd3-b1e7-1d3e7456d295","console":"info","time":"2021-05-14T09:33:23+08:00","message":"======= received hot key. pressed: true"}
{"level":"info","system":"authenticated application","system":"secureloops","loopID":"70fb422c-eb8c-4cd3-b1e7-1d3e7456d295","console":"info","time":"2021-05-14T09:33:23+08:00","message":"======= received hot key. pressed: true"}
{"level":"info","system":"authenticated application","system":"secureloops","loopID":"70fb422c-eb8c-4cd3-b1e7-1d3e7456d295","console":"info","time":"2021-05-14T09:33:23+08:00","message":"======= received hot key. pressed: true"}
{"level":"info","system":"authenticated application","system":"secureloops","loopID":"70fb422c-eb8c-4cd3-b1e7-1d3e7456d295","console":"info","time":"2021-05-14T09:33:24+08:00","message":"======= received hot key. pressed: true"}
{"level":"info","system":"authenticated application","system":"secureloops","loopID":"70fb422c-eb8c-4cd3-b1e7-1d3e7456d295","console":"info","time":"2021-05-14T09:33:24+08:00","message":"======= received hot key. pressed: true"}
{"level":"info","system":"authenticated application","system":"secureloops","loopID":"70fb422c-eb8c-4cd3-b1e7-1d3e7456d295","console":"info","time":"2021-05-14T09:33:24+08:00","message":"======= received hot key. pressed: true"}
{"level":"info","system":"authenticated application","system":"secureloops","loopID":"70fb422c-eb8c-4cd3-b1e7-1d3e7456d295","console":"info","time":"2021-05-14T09:33:24+08:00","message":"======= received hot key. pressed: true"}
```
No logs with `pressed: false`.
- Olive Helps version: 0.16.2
- LDK version: 3.0.0-beta.1
- Operating system: Windows 10 x64 professional built 19041.928

**Comment by richseviora** [comment]
FYI @hans-hsieh-asus I've identified the bug and have a fix pending internally. I'll let you know when the fix will be available in production (very likely next release)

**Comment by richseviora** [comment]
Hi Hans, quick update on this:

We've fixed the bullet 2 issue where a hotkey (Ctrl+Shift+A) would be called when a subsets of that hotkey (Ctrl+A) is pressed in the version released today.

The bullet 3 issue where multiple key presses would be triggered when held down was a fun one. The repeat calls with `pressed: true` is actually legitimate behaviour, so what we did instead was to report the key release as well. So if authors want to detect long presses, they need to check when the returned value is `true` or `false`. This will be in the next release.

**Comment by hans-hsieh-asus** [comment]
> Hi Hans, quick update on this:
> 
> We've fixed the bullet 2 issue where a hotkey (Ctrl+Shift+A) would be called when a subsets of that hotkey (Ctrl+A) is pressed in the version released today.
> 
> The bullet 3 issue where multiple key presses would be triggered when held down was a fun one. The repeat calls with `pressed: true` is actually legitimate behaviour, so what we did instead was to report the key release as well. So if authors want to detect long presses, they need to check when the returned value is `true` or `false`. This will be in the next release.

Sorry, I missed your comment. That sounds good to us. 👍

**Comment by CandiceCLB** [comment]
The fix was released with Olive Helps V.18.10. Closing this issue.
