### ISSUE TITLE
Allow network aptitude to make http calls for local devleopment

### ISSUE THREAD

**Issue by IanKrieger** [open-olive/loop-development-kit#165]
"As a loop author, I would like a way to make http calls from the network aptitude so that I can use local endpoints for development"

The network aptitude currently only allows for `https` calls to be made. This does not allow for an easy way to hit `localhost` from a loop installed locally for development purposes. It would be nice if some sort of method or override was provided that allowed for `http` calls to made in local loops for faster development iterations.

**Comment by cshields-oliveai** [comment]
@IanKrieger - Thank you for this request! We feel that enabling this functionality for testing a Loop locally is valuable. We have created an internal task for this: SIDE-2231.

We will give an update when this task is complete and ready for release here.

**Comment by cshields-oliveai** [comment]
@IanKrieger - with the latest Olive Helps (V 0.17.3) and the LDK (V 3.0.0.beta-3), calls to `localhost` are now possible for **local loops**. Make sure to declare `localhost` as part of your network permissions for local testing:

```json
"network": {
    "urlDomains": [
      {
        "value": "localhost"
      }
    ]
  }
 ```

Thank you for reporting.
