### ISSUE TITLE
Link component `href` and `onClick` issues

### ISSUE THREAD

**Issue by kdouglass-oliveai** [open-olive/loop-development-kit#166]
If `href` is provided the link does not click through.
If `onClick` is omitted an error is thrown.

**Error**
`{"level":"error","system":"authenticated application","system":"secureloops","loopID":"73893405-b802-4932-958c-7e1cd95faf08","console":"error","time":"2021-05-07T16:33:21-04:00","message":"Unhandled promise rejection GoError: invalid whisper object: error building components: error asserting callback: <nil>"}`

**Example of code**
```js
clipboard.listen(true, (incomingText: string) => {
            whisper.create({
                label: 'Clipboard Text Whispers',
                onClose: () => {
                    console.log("Closed Clipboard Text Whisper");
                },
                components: [
                    {
                        href: 'https://oliveai.com',
                        // onClick: () => {
                        //     console.log('Clicked link')
                        // },
                        text: 'External link',
                        style: Urgency.None,
                        type: whisper.WhisperComponentType.Link,
                    }
                ]
            });
        });

**Comment by kdouglass-oliveai** [comment]
Great, thanks!

**Comment by CandiceCLB** [comment]
LDK version V.3.0.0.beta-3 and Olive Helps version V0.17.3 have been released. These updates should resolve your issue. if you find this is still outstanding, please feel free to reopen.
