### ISSUE TITLE
Email component tooltip not working

### ISSUE THREAD

**Issue by kdouglass-oliveai** [open-olive/loop-development-kit#169]
No tooltip appears for the email component upon hover.

```js
{
    label: 'Email label',
    value: 'Test default value',
    tooltip: 'This is a tip', 
    onChange: (value) => {
       console.log('Email value changed', value)
    },
    type: whisper.WhisperComponentType.Email
}

**Comment by RusGraf** [comment]
Hello  @kdouglass-oliveai,
Thank you for pointing this out. I'm able to see a tooltip for the email whisper component in the latest build. This should be fixed with the next LDK/OliveHelps release.

**Comment by CandiceCLB** [comment]
This has been resolved. Please update to the latest versions of Olive Helps (V 0.17.3) and the LDK (V 3.0.0.beta-3). If you are still seeing this problem, please re-open this issue.
