### ISSUE TITLE
Add development mode config

### ISSUE THREAD

**Issue by latman-oliveai** [open-olive/loop-development-kit#181]
Builds can take up to more than 7 seconds with the current LDK webpack config. 

I edited the config to turn off minimization, enable able caching, excluding node_modules from babel, and like clockwork, my builds were reduced to less than 2.5 seconds with webpack --watch builds happening in under 900 milliseconds. 

Here is the current time breakdown with the current config for a cold build:
 

```
 SMP  ⏱  
General output time took 7.43 secs

 SMP  ⏱  Plugins
TerserPlugin took 1.89 secs
BannerPlugin took 0.001 secs
DefinePlugin took 0.001 secs

 SMP  ⏱  Loaders
babel-loader took 5.11 secs
  module count = 249
ts-loader took 2.67 secs
  module count = 9
handlebars-loader took 1.33 secs
  module count = 2

```

After edits:
```

 SMP  ⏱  
General output time took 2.54 secs

 SMP  ⏱  Plugins
BannerPlugin took 0.002 secs
DefinePlugin took 0 secs

 SMP  ⏱  Loaders
ts-loader took 1.6 secs
  module count = 9
modules with no loaders took 1.057 secs
  module count = 231
babel-loader took 0.381 secs
  module count = 2
handlebars-loader took 0.251 secs
  module count = 2

```

**Comment by RusGraf** [comment]
Thank you for bringing it up @latman-oliveai, we will prioritize this as an enhancement and update this issue when it is done.

**Comment by EddieAtOlive** [comment]
@latman-oliveai since you already have the modified config, you're welcome to put in a pull request and we can review it. Otherwise, we'll add it to our list like @RusGraf said.

**Comment by CandiceCLB** [comment]
HELPS-454

**Comment by CandiceCLB** [comment]
This issue has been resolved with the LDK release of V.3.0.2. Please update to the latest version. If you find you still have issue, please reopen with comment.
