### ISSUE TITLE
`@babel/plugin-transform-runtime` drastically increases the build size

### ISSUE THREAD

**Issue by kdouglass-oliveai** [open-olive/loop-development-kit#184]
The new LDK could not find `@babel/plugin-transform-runtime` with yarn. Installing it as a dev dependency increases the unminified build size 500kb+. Webpack's build time went from < 1s to > 5s.

`webpack 5.37.0 compiled in 5336 ms`

```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (500 KiB).
This can impact web performance.
Assets: 
  loop.js (717 KiB)

**Comment by RusGraf** [comment]
Thank you @kdouglass-oliveai, I'll create a card to investigate this scenario.

**Comment by kdouglass-oliveai** [comment]
Thanks @RusGraf. You can refer to [issue 181](https://github.com/open-olive/loop-development-kit/issues/181) for more details on the compile time.

**Comment by CandiceCLB** [comment]
Closing this card as it is being tracked in issue 181 stated above.
