### ISSUE TITLE
Filesystem or system Aptitude: Open file

### ISSUE THREAD

**Issue by latman-oliveai** [open-olive/loop-development-kit#185]
We would like to open a file with the default viewing applications for search style loops. For instance, if we search and index an excel file, it would be cool to allow the user to open the source file in Microsoft Excel.

It would be cool to open a file in the application and open a finder/windows explorer/file browser. 

system.openFile(path)
system.openFileBrowser(path)

**Comment by RusGraf** [comment]
Hello @latman-oliveai. I'll create a feature request on our board. Thanks for the suggestion.

**Comment by CandiceCLB** [comment]
HELPS-456

**Comment by CandiceCLB** [comment]
This issue was resolved with the release of LDK V3.2.0. Closing out this issue.
