### ISSUE TITLE
Missing LDK key throws unhelpful error message

### ISSUE THREAD

**Issue by latman-oliveai** [open-olive/loop-development-kit#187]
Missing LDK key entirely doesn't throw a helpful error:
` TypeError: Cannot convert undefined or null to object`

Fix:
https://github.com/open-olive/loop-development-kit/pull/186

**Comment by epiccoleman** [comment]
Marked as resolved. Thanks for the PR @latman-oliveai !

**Comment by richseviora** [comment]
This change has been released in v3.0.0-beta.4. Thank you again for the contribution Michael!
