### ISSUE TITLE
OliveHelps auto-update doesn't restart normally

### ISSUE THREAD

**Issue by hans-hsieh-asus** [open-olive/loop-development-kit#189]
For Mac, after a user clicks *update* to do auto-update for OliveHelps, I can only force terminate OH and manually install the latest version from the website. Here're the steps to reproduce:
1. installed older version
   MD5: 67deaef2009ea3226522a4419b999107
   SHA: e2e14dec6313a420583270989bad4582429816eb
1. launch OH and sign in, OH ask me to update
1. click on "update", the OH UI disappear
1. only OH process and icon on dock were visible, but no any UI even I click on the icon
1. after about 15 min, the situation remained
1. manually download OH from web
   MD5: 35f1e5576b2a567b4ebc2856a601b396
   SHA: 4250f81ef658de18b1062f7973d678fd3fb0b15a
1. manually install OH, and force terminate previous OH process
1. restart OH, it was back to normal.

On Windows, there's a similar problem.
After the auto-update, I have to kill processes `olivehelps.exe` and `.olivehelps.exe.old`, and run OH again. Otherwise, OH sidebar won't show up even if I try to launch OH.
OS: Windows 10 x64 build 19041.985
OliveHelps version: 0.16.2 -> 0.17.3

**Comment by epiccoleman** [comment]
Hi @hans-hsieh-asus , thanks for submitting this issue. 

We are tracking work on this problem internally with SIDE-1780.

**Comment by hans-hsieh-asus** [comment]
I didn't see this issue in new versions. Closing it. Thanks.
