### ISSUE TITLE
Helps sidebar closes unexpectedly when using global search 

### ISSUE THREAD

**Issue by latman-oliveai** [open-olive/loop-development-kit#207]
![EB524581-47E9-4ABF-84DE-8C7991C6C3C5](https://user-images.githubusercontent.com/83671673/120553071-1056d880-c3c6-11eb-8e62-27cebe8d5db3.gif)
 
 When sidebar is open and you do a global search we expect the sidebar to stay open. In the latest release, helps closes on subsequent global search hiding any whisper dispatched during the animation.

**Comment by cshields-oliveai** [comment]
Thanks @latman-oliveai - we will create an internal task for this and keep you updated when it is resolved.
