### ISSUE TITLE
Cannot update whisper color strip for local loop

### ISSUE THREAD

**Issue by hans-hsieh-asus** [open-olive/loop-development-kit#216]
It looks like we aren't able to update the whisper color strip for an existing local loop.
Steps to reproduce:
- Install a local loop
- Update the loop in the Loop Library to change the color of the whisper strip.
- Click `Update local loop` button
- Restart the loop
- The color of the whisper strip is not changed.

**Comment by cshields-oliveai** [comment]
@hans-hsieh-asus : We've generated a new internal task for this one as well: SIDE-2488. We will keep you up to date on priority / resolution.

**Comment by CandiceCLB** [comment]
Updating ticket number for tracking: HELPS-274

**Comment by BrettMugglinOlive** [comment]
Updating ticket number again to HELPS-1353

**Comment by MaggieMaSS** [comment]
This is no longer an issue and I'm going to close this issue!
