### ISSUE TITLE
JWT token of User aptitude doesn't encode a unique user ID

### ISSUE THREAD

**Issue by hans-hsieh-asus** [open-olive/loop-development-kit#218]
If I decode the JWT token obtained from the `User` aptitude, I can get something like:
```json
{
  "header": {
    "alg": "RS256",
    "typ": "JWT"
  },
  "payload": {
    "azp": "aaaaaaaa-cccc-dddd-eeee-ffffffffffffff.loop.oliveai.com",
    "exp": 1622714197,
    "iss": "https://sidekick.oliveai.com/api/user/createJWT",
    "sub": "test@example.com"
  }
}
```
The `sub` field is the user's email instead of a unique user ID. We want to obtain a unique user ID that won't change even if the user changes his email.
And the JWT token cannot be validated using the public keys available at https://login.oliveai.com/.well-known/jwks.json

p.s. This is the same issue I reported in Slack. I just create this one to help to track.

**Comment by cshields-oliveai** [comment]
Hello @hans-hsieh-asus - Thanks for reporting this. We have work in progress to update `sub` to be a unique userId. The internal task for this is: SIDE-2454 and is scheduled to go out with our next OH release.

**Comment by hans-hsieh-asus** [comment]
Thanks. I see the new user JWT token now has a user ID as the `sub`.

**Comment by EddieAtOlive** [comment]
Glad you noticed! You're correct, the issued JWTs should now have a unique ID in the `sub` claim and the user's current email address has been moved to a non-standard claim called `email` too.
