### ISSUE TITLE
Markdown doesn't support HTML elements

### ISSUE THREAD

**Issue by hans-hsieh-asus** [open-olive/loop-development-kit#223]
In CommonMark syntax, it is allowed to have HTML elements. And following the discussion [here](https://talk.commonmark.org/t/can-we-have-formal-escaping-rules/2624), we can use `<div>` to escape the text which we don't want to be rendered as markdown.  
However, it looks like the `Markdown` component doesn't support HTML elements. If I use the code below,
```javascript
const {whisper} = require('@oliveai/ldk');
await whisper.create({
  label: 'test',
  components: [
    {
      type: whisper.WhisperComponentType.Markdown,
      body: `<div>\n- 123<br>\n- 456<br>\n</div>`,
    },
  ],
  onClose: () => {},
});
```
I see 
![image](https://user-images.githubusercontent.com/68371064/121767029-6b3bbd00-cb88-11eb-9b49-a419d1b04f46.png)
And if I use the same text in https://spec.commonmark.org/dingus/ , I see
![image](https://user-images.githubusercontent.com/68371064/121767045-86a6c800-cb88-11eb-9898-c564522b4bd4.png)
Is the Markdown implementation of LDK based on an older version of the spec?

**Comment by epiccoleman** [comment]
Hi Hans,

I did some digging around in the code this morning. The library that we use for rendering Markdown escapes HTML in Markdown by default for security reasons. 

Based on discussion with the team, we do not currently plan to support HTML in Markdown, so at this time, this is the expected behavior. 

Is your team looking at this as a solution primarily for the purposes of escaping special characters?

**Comment by hans-hsieh-asus** [comment]
> Hi Hans,
> 
> I did some digging around in the code this morning. The library that we use for rendering Markdown escapes HTML in Markdown by default for security reasons.
> 
> Based on discussion with the team, we do not currently plan to support HTML in Markdown, so at this time, this is the expected behavior.
> 
> Is your team looking at this as a solution primarily for the purposes of escaping special characters?

Yes. We want to use it to escape characters that may be accidentally rendered as Markdown. I understand you may want to disable HTML for security. For our current use case, it's not a strong requirement for escaping. Therefore, let me close this issue. Thank you for checking the code for us. :)
