### ISSUE TITLE
Need loops example code

### ISSUE THREAD

**Issue by alokmishra1** [open-olive/loop-development-kit#234]
I am new to LDK, i need example codes to start with.

**Comment by EddieAtOlive** [comment]
Hi @alokmishra1. There are two easy ways to get started.

**VS Code Extension**
A really simple way to get started is to use our [VS Code Extension](https://vscode.oliveai.dev/). If you don't use VS Code and don't want to start using it, then this version obviously won't help you much. But if you do, it lets you create your entire repo structure with examples that use whatever Aptitudes you want.

![VS Code Extension Screenshot](https://github.com/open-olive/vscode-loop-development-kit/raw/HEAD/images/createLoopUi.png)

**Examples**
There are also a few examples in our [GitHub repo](https://github.com/open-olive/loop-development-kit/tree/main/ldk/javascript/examples) for you to reference. The [typescript-loop](https://github.com/open-olive/loop-development-kit/tree/main/ldk/javascript/examples/typescript-loop) and the [javascript-loop](https://github.com/open-olive/loop-development-kit/tree/main/ldk/javascript/examples/javascript-loop) are very simple Loops for you to get started with depending on which language you prefer. And the [universal-example-loop](https://github.com/open-olive/loop-development-kit/tree/main/ldk/javascript/examples/universal-example-loop) is a little more complex.

**More reading**
If you haven't read it yet, you can follow the [getting started page on our Developer Hub](https://oliveai.dev/guides/getting-started). There is also a short [troubleshooting guide](https://oliveai.dev/guides/troubleshooting) on the Developer Hub if you have issues, but always feel free to ask questions here, too.
