### ISSUE TITLE
After adding new custom loop through local loops, loop gets installed but it says error in starting

### ISSUE THREAD

**Issue by alokmishra1** [open-olive/loop-development-kit#235]

**Comment by alokmishra1** [comment]
![image](https://user-images.githubusercontent.com/72005525/122546809-f5829600-d04c-11eb-9d1b-cec7d59f27dc.png)
This error comes after installing loop application through local loops

**Comment by EddieAtOlive** [comment]
@alokmishra1 Sorry you're having trouble getting started. We'll need some information from your logs before we can assist you. You can find out how to view the logs and do some troubleshooting in our [troubleshooting guide](https://oliveai.dev/guides/troubleshooting).

If the errors you find don't help you resolve the problem on your own, feel free to post the errors here (stripped of any sensitive information) and we'll try to help. Let us know how it goes.

**Comment by alokmishra1** [comment]
I am getting the same error. please find the attached log file. 
[Olive Helps-0.19.0.log](https://github.com/open-olive/loop-development-kit/files/6691893/Olive.Helps-0.19.0.log)

please help me in troubleshooting the error.

**Comment by epiccoleman** [comment]
@alokmishra1 can you share the version of the LDK that you're currently using?

**Comment by alokmishra1** [comment]
Ldk version 3.0.1

**Comment by epiccoleman** [comment]
@alokmishra1 After some investigation today we discovered a bug in LDK 3.0.1 that may have been the cause of this problem. We have taken down the 3.0.1 release and published 3.0.2, which fixes the issue.

When you have some time, please try updating to 3.0.2, and let us know if this resolves your problem. Thanks!

**Comment by alokmishra1** [comment]
The problem resolved when I updated the LDK version to 3.0.2. Thanks for helping.

**Comment by epiccoleman** [comment]
@alokmishra1 Thanks for your patience and for checking out 3.0.2 for us. I'm glad you were able to get things working.
