### ISSUE TITLE
Allow specifying HTTP request timeout

### ISSUE THREAD

**Issue by hans-hsieh-asus** [open-olive/loop-development-kit#240]
It looks like when sending an HTTP request, the default timeout is 5 sec.
Is it possible to specify the timeout?

**Comment by epiccoleman** [comment]
Hello Hans! It's not currently possible for Loop Authors to configure the httpRequest timeout. 

This is something we'd like to add in the near future. We have created SIDE-2574 to track this feature internally. Thanks for your suggestion!

**Comment by richseviora** [comment]
This is now HELPS-112

**Comment by hans-hsieh-asus** [comment]
It's resolved in the new LDK. Thanks.
