### ISSUE TITLE
Different permission for each environment

### ISSUE THREAD

**Issue by hans-hsieh-asus** [open-olive/loop-development-kit#252]
LDK requires us to put the permission declaration in `package.json` like
```json
{
  "ldk": {
    "permissions": {
      "network": {
        "urlDomains": [
          {
            "value": "myservice-prod.example.com"
          },
        ]
      }
    }
  }
}
```
However, we want to have different declarations for different environments. For example, for stage environment, we may want to allow `myservice-stage.example.com`. Though putting all of them will work, we don't want to let the users see the weird `myservice-stage.example.com`.
Is it possible to specify the permission programmatically or put the declarations of each environment in different files, and specify which one to use using environment variable or command line?

**Comment by hans-hsieh-asus** [comment]
It looks like I find a workaround. I define my own `webpack.config.js` like
```javascript
const merge = require('webpack-merge');
const ldkConfig = require('@oliveai/ldk/dist/webpack/config');
const {generateBanner} = require('@oliveai/ldk/dist/webpack/generate-banner');
const webpack = require('webpack');
const config = require('config');

const merged = merge.merge(ldkConfig.default, {
  plugins: [
    new webpack.BannerPlugin({
      banner: generateBanner({
        'ldk': {
          'permissions': {
              // something interesting
          },
        },
      }),
      raw: true,
    }),
  ],
});
module.exports = merged;
```
And in `package.json`, put a dummy `"ldk": {"permissions": {}}"`.  
With all above, two banners will be generated on top of the `loop.js`, but it looks like only the first one will be used, so it works. :)
I can then use libraries like `node-config` to use different permission declarations for different environments.
It doesn't sound like a bad solution actually. But it would still be good if there's a more elegant way.
Feel free to close this issue if it is determined to be the right way to go. :)

**Comment by richseviora** [comment]
Thanks for the feedback Hans! We hadn't considered this need and will look to see how we can address it. It sounds like your workaround is working for you right now so please keep using it until we deliver a better solution :)

One idea that comes to mind is adding support for configuration via [Cosmiconfig](https://github.com/davidtheclark/cosmiconfig#installation), which would allow you to add programmatic config via a JS file.  HELPS-829 has been created for tracking purposes.
