### ISSUE TITLE
The window of loop library too big to hit close button on Mac

### ISSUE THREAD

**Issue by JonasChengAsus** [open-olive/loop-development-kit#262]
I'd like to report an issue on Mac, the window of loop library too big to hit close button, need to resize the window and move around to workaround.

I took a video clip to illustrate the issue.

https://aics-olive.slack.com/files/U01TY7DJT7E/F026T1G6NBU/screen_recording_2021-07-01_at_7.05.56_pm.mov

**Comment by richseviora** [comment]
Hi Jonas, thanks for reporting this! I've opened HELPS-833 to fix this bug and we'll let you know when we have a fix in place.
