### ISSUE TITLE
Window focus and window close functionality

### ISSUE THREAD

**Issue by alokmishra1** [open-olive/loop-development-kit#263]
Can we make any windows focus and can we close any window in LDK application. As i have seen only we can read window changes.

**Comment by alokmishra1** [comment]
Any particular way, by which we can make a particular window focus (active). And close some window by any means.

**Comment by richseviora** [comment]
Hi Alok! Thanks for opening this issue. We don't yet support the ability to programmatically focus or close specific windows. Can you give us a sense of how you'd use this in a Loop?

Also, I don't recognize your name - are you with an existing Olive Helps partner or are you one of the first developers to wander in and give Olive Helps a whirl? :)

**Comment by alokmishra1** [comment]
We are to be partner and I am working on some functionality.

**Comment by richseviora** [comment]
We've created HELPS-980 to track this feature request. We'd like to better understand the business value these two capabilities could offer; can you briefly describe how the Loop would use these two features in the business process?

**Comment by alokmishra1** [comment]
If we are making an exam invigilator loop, we can track if the user is moving away from the exam window and with the window focus feature, we can make the exam window focused to the user. One more use case is for data entry operator, if operator be away from the data entry application for more than 5 min then we forcely focus the data entry application to the operator.

**Comment by CandiceCLB** [comment]
Olive Helps has decided not to support this feature at this time.
