### ISSUE TITLE
TextInput label overlapped with text value

### ISSUE THREAD

**Issue by hans-hsieh-asus** [open-olive/loop-development-kit#264]
I'm using LDK 3.1.0.
Here's the sample code I used.
```javascript
  const {whisper} = require('@oliveai/ldk');
  const onChange = async (err, value) => {
    await textWhisper.update({
      label: 'Hello world',
      components: [
        {
          type: whisper.WhisperComponentType.TextInput,
          id: 'my-text',
          key: 'my-text',
          label: 'label',
          onChange,
        },
      ],
    });
  };
  const textWhisper = await whisper.create({
    label: 'Hello world',
    onClose: () => {},
    components: [
      {
        type: whisper.WhisperComponentType.TextInput,
        id: 'my-text',
        key: 'my-text',
        label: 'label',
        value: 'some value',
        onChange,
      },
    ],
  });
```
If I add more text to the `TextInput` and let the `TextInput` lose focus, I will see:
![image](https://user-images.githubusercontent.com/68371064/124411932-0dae2100-dd80-11eb-82e5-3483b84bb411.png)
If I set the `value` property when doing the update, it won't have such a problem.
By the way, it looks like when doing an update, if we don't set the `value` property, the original text of the `TextInput` will be kept. Do you suggest we always set the `value` even if we don't want to update it? Or, only set that property when we want to update the value?

**Comment by DanielWagersOlive** [comment]
Hi @hans-hsieh-asus.

I'll open a bug for the label overlap.  Probably just another styling issue.

To answer your follow-up question, I asked the team what they would suggest.  The following is what I got in response:

> The value property should only be set when you want a default value. This goes for whisper.create() as well as whisper.update() calls.

> If a value is set on a component prior to a whisper.update() call, it will be treated as a new "default value."

> If they need all components to be cleared upon update, their best bet is to set values to empty prior to calling update.

**Comment by DanielWagersOlive** [comment]
HELPS-839 has been opened. We'll let you know when we have resolved the issue.

**Comment by epiccoleman** [comment]
Hi Hans. As Dan suspected, this was a styling issue. We've resolved the problem for the next version of Olive Helps. Thanks for the report!
