### ISSUE TITLE
TextInput label overlapped with outline

### ISSUE THREAD

**Issue by hans-hsieh-asus** [open-olive/loop-development-kit#265]
I'm using LDK 3.1.0.
When the label of a `TextInput` is long, and the `TextInput` is focused, it looks like the label will overlap with the outline like below:
![image](https://user-images.githubusercontent.com/68371064/124422215-8cfa1f80-dd95-11eb-9b2e-d0be82a2132d.png)
The longer the text, the overlapped area becomes larger.

**Comment by DanielWagersOlive** [comment]
Hi @hans-hsieh-asus.

This looks like a style related issue.  We'll probably open a bug for it.

**Comment by DanielWagersOlive** [comment]
HELPS-838 has been opened.  We'll let you know when we have resolved the issue.

**Comment by epiccoleman** [comment]
Hi Hans. We've resolved this problem for the next version of Olive Helps. Thanks for the report!
