### ISSUE TITLE
Long search text for OH searchbar is displayed improperly

### ISSUE THREAD

**Issue by hans-hsieh-asus** [open-olive/loop-development-kit#269]
When I use the search bar of the sidebar or global search to search a very long text, all the text will be displayed in the sidebar. And it may overlap the whispers in the sidebar. E.g.
![image](https://user-images.githubusercontent.com/68371064/125067961-7d593e80-e0e7-11eb-89f4-fe7d129e4b81.png)
Would it be better that it only shows a prefix after `Searched for: ` ?

**Comment by DanielWagersOlive** [comment]
Looks like another styling / rendering issue!  I'll open a bug.

**Comment by DanielWagersOlive** [comment]
HELPS-866 has been opened. We'll let you know when we have resolved the issue.
