### ISSUE TITLE
Detect copy from list pair 

### ISSUE THREAD

**Issue by hans-hsieh-asus** [open-olive/loop-development-kit#272]
List pair allows a user to click-to-copy the label or the value. But it doesn't allow the loop to detect that the user has clicked to copy.
Is it possible to add the feature?

**Comment by RusGraf** [comment]
Thank you for the request Hans,
HELPS-878 was added to track it. Do you mind describing how this feature would be used? Also would you expect a callback when clik-to-copy is used?

**Comment by hans-hsieh-asus** [comment]
> Thank you for the request Hans,
> HELPS-878 was added to track it. Do you mind describing how this feature would be used? Also would you expect a callback when clik-to-copy is used?

@RusGraf We want to do user statistics to see the number of ICDs copied for a medical record to decide whether users are satisfied with our prediction result.
Having a callback when a user click-to-copy would be good. Any other way to notify our loop is also fine. And we also want to distinguish whether the user clicks the label or the value. Whether the callback would be called when the label or the value is not copyable doesn't matter in our use case.
Thanks.

**Comment by RusGraf** [comment]
@hans-hsieh-asus thank you for the clarification. It sounds like this is more of the analytics purpose than functional. I'll update the HELPS-878 and we will prioritize this work.

**Comment by CandiceCLB** [comment]
This has been resolved with the latest LDK version, V3.2.0.
