### ISSUE TITLE
Oval shadow of radio button

### ISSUE THREAD

**Issue by hans-hsieh-asus** [open-olive/loop-development-kit#283]
Hi, I got a suggestion from our designer.
For the radio group whisper component, when the mouse is moved over, there's an oval shadow. Would it be better if the shadow is changed to a circle?
![image](https://user-images.githubusercontent.com/68371064/126151133-37e9077a-f1bd-4b51-a1c3-9296b4f1b0ae.png)

**Comment by RusGraf** [comment]
Hello Hans, thank you for the suggestion. HELPS-911 was created to track this request.

**Comment by CandiceCLB** [comment]
This issue has been resolved with the release of LDK v3.2.0.
