### ISSUE TITLE
Network aptitude (web sockets)

### ISSUE THREAD

**Issue by charles-circulo** [open-olive/loop-development-kit#286]
* `socket.setCloseHandler` is not called when:
  * user logs out, but doesn't close olive helps
  * local loop restart
* it is called when:
  * user logs out, then closes window
  * user quits olive helps from hamburger menu

Observed that if user 1 logs out and does not close the Olive Helps window, user 2 can log in and web socket for user 1 is still live and user 2 will receive messages for user 1.

**Comment by epiccoleman** [comment]
Hi @charles-circulo, thanks for bringing this to our attention. I've created HELPS-917 for us to track this work internally. We'll update this issue when we have a fix.

**Comment by CandiceCLB** [comment]
Resolved with OH v0.22.3
