### ISSUE TITLE
The application “Olive Helps” could not be launched because a miscellaneous error occurred (OSStatus -10817)

### ISSUE THREAD

**Issue by adrianbj** [open-olive/loop-development-kit#296]
Hi there,

I am getting this error when trying to run OliveHelps on HighSierra (yes, I know it's old - will be updating when new Macbook Pro comes out later this year).

Any ideas whether this is related to my OS or is it something else? Do you think it might be fixable?

Thanks.

**Comment by cshields-oliveai** [comment]
Hello @adrianbj - Can you fetch the entire log for us from Olive Helps? (see [this guide](https://oliveai.dev/guides/troubleshooting) for information on retrieving the log).

**Comment by adrianbj** [comment]
@cshields-oliveai - I don't think it's getting that far - no log file is being created. If I try to run it from the command line I get this error:
```
LSOpenURLsWithRole() failed with error -10825
```

which looks like it is related to this: https://forum.qt.io/topic/77038/lsopenurlswithrole-failed-with-error-10825/2

Any chance you could `make` it with a lower value for `-mmacosx-version-min` ?

**Comment by richseviora** [comment]
Thanks for reporting this issue Adrian! We've created issue HELPS-962 to track this issue; we'll let you know when this is resolved. Not sure what the timeframe will look like yet.

**Comment by adrianbj** [comment]
Thanks for the update @richseviora - any chance you could narrow down the timeframe to days, weeks, or months? I have to create a loop fairly shortly, so just trying to figure out my options. Is the source code for the app available so I could try compiling it myself?

**Comment by BrettMugglinOlive** [comment]
I'm sorry we didn't get back to you in a more timely manner, but with the release of LDK 3.7.0 and OH 0.27.x, we transitioned away from using `astilectron` as the underlying executable to using vanilla `electron`. According to their documentation, the lowest MacOS version they support is 10.11, so in theory this is our lower bound of support as well. This also means that the problem you were observing should be addressed!

With that, I'm going to go ahead and close this thread, but please reopen it if this is still an issue for you.
