### ISSUE TITLE
Prevent sidebar hide while typing in a form (or cursor in form?)

### ISSUE THREAD

**Issue by e-rotera** [open-olive/loop-development-kit#319]
If you have your sidebar settings to auto-hide, it can be really annoying if your mouse happens to stray off the Helps application and you are actively typing in a form and then the sidebar hides. I'd recommend that the 3 second count include 3 seconds after the last keystroke in a form field, not just 3 seconds from mouse hover.

**Comment by cshields-oliveai** [comment]
Thanks for the suggestion @e-rotera. I'll bring this back to the team and determine if / when this can get into our team backlog and I will update you here.

**Comment by CandiceCLB** [comment]
HELPS-1288
