### ISSUE TITLE
FileInfo ModTime Property is

### ISSUE THREAD

**Issue by alexmatthew-olive** [open-olive/loop-development-kit#337]
In the type definition of FileInfo [modTime](https://github.com/open-olive/loop-development-kit/blob/main/ldk/javascript/src/filesystem/types.ts) is a string but when I tried to use string methods on it, it would cause an error.

When I log the `typeof modTime` it is actually an object

```
// code for log inside an async function 
 const stat = await filesystem.stat(filepath);
 console.log('modTime typeof', typeof stat.modTime);
      
// Logs
 modTime typeof object 
```

**Comment by RusGraf** [comment]
@alexmatthew-olive, I captured this details in HELPS-1456 so we could prioritize it. Thanks for reporting this issue.
