### ISSUE TITLE
FileInfo modTime Format is not supported by goja 

### ISSUE THREAD

**Issue by alexmatthew-olive** [open-olive/loop-development-kit#338]
When I use the modTime (after using `JSON.stringify()`)  in a `new Date(modTime)` it returns invalid date
it appears goja does not support the same `Date` formats as node as the string it returns does seem to work on node
```
// Code for log
  const stat = await filesystem.stat(filePath);
  console.log('modTime toString', JSON.stringify(stat.modTime));
  console.log('modTime Passed into newDate', new Date(JSON.stringify(stat.modTime)));

// Logs     
 modTime toString "2021-09-10T12:09:17.309693098-04:00" 
 modTime Passed into newDate Invalid Date
```

**Comment by RusGraf** [comment]
Hey @alexmatthew-olive , I created the card HELPS-1455 to prioritize this work. Thanks for reporting this.
