### ISSUE TITLE
Support for `fetch()` for accessing HTTP resources

### ISSUE THREAD

**Issue by KeithMHughesRoteraAI** [open-olive/loop-development-kit#340]
At the moment, the network aptitude must be used for any network access. There are many libraries which assume a browser or Node environment which provide a `fetch()` API for accessing HTTP resources so that they can hide the network access and provide, for example, a GraphQL client library where you give the server URL for the GraphQL endpoint and nothing else.

This complicates development because it would become necessary for fork these projects, locate the `fetch()` usage and replace it.

Some libraries I want to use:
- https://www.npmjs.com/package/graphql-request
- https://www.npmjs.com/package/@azure/msal-browser

**Comment by epiccoleman** [comment]
Hi Keith! Thanks for the feedback.

We've created HELPS-1482 to evaluate this suggestion. We'll update this issue with any relevant information.

**Comment by coltonbrugger** [comment]
We at Circulo certainly seek more-open networking capabilities as well. We would've implemented things very differently (and likely faster) if we could plug in other libraries which have their own network/caching/retry/related tooling bundled in.

**Comment by KeithMHughesRoteraAI** [comment]
Though this is primarily about `fetch()` I wonder how many other similar APIs are available in browser/Node environments that complicate using existing libraries and force either a fork or roll your own solution. @coltonbrugger have you folks at Circulo run into anything else?

**Comment by BrettMugglinOlive** [comment]
Just trying to close the loop on this thread, we have since completed this work. While we didn't provide the fetch API within the framework, we have created an example showing how to polyfill fetch into your loop! You can find that [here](https://github.com/open-olive/loop-development-kit/tree/main/ldk/javascript/examples/fetch).

Closing this thread, but feel free to reopen.

**Comment by KeithMHughesRoteraAI** [comment]
Many thanks for providing the example!

Any reason to not make it part of the LDK? It is a standard part of a
variety of Javascript environments, so would make sense being part of the
Olive Helps Javascript environment.

**Comment by KeithMHughesRoteraAI** [comment]
Understood.

I would argue that as you are providing a browser type environment, you
should be providing a complete fetch implementation as you are making it
harder to use existing libraries in the Js/ts world. If your goal is to get
lots of loops, you need to support your developers and how they will
develop.

I understand you need to figure out your priorities with limited resources,
but if you don't support your developers, you don't have a rapidly
expanding library of loops because it is so much work to reinvent
everything.
