### ISSUE TITLE
File does not appear in Dropzone after selecting from "browse" option if the "accept" DropZoneProp is specified.

### ISSUE THREAD

**Issue by IanKrieger** [open-olive/loop-development-kit#341]
When I click "browse" inside of the Dropzone component, after selecting a file it does not appear to attach to the component.

This happens when the `accept` prop is specified.

Steps to reproduce:
- Add `accept` to Dropzone config
- Attempt to browse for file and select it

```
{
    accept: ['pdf' ...]
    ...
};
```

Example:
---

https://user-images.githubusercontent.com/48930920/133310841-1cd1c653-03b6-4415-b7a5-d60ebe203556.mov

**Comment by epiccoleman** [comment]
Hi Ian - I just tried to reproduce this bug, and I was not able to. Would you be able to share your Loop code to help us narrow things down?

**Comment by BrettMugglinOlive** [comment]
Closing, but if there was an issue, it may have been fixed in 3.7.0 by HELPS-1923. If not, please reopen this thread.
