### ISSUE TITLE
Websocket implementation is not supporting PING/PONG messages

### ISSUE THREAD

**Issue by KeithMHughesRoteraAI** [open-olive/loop-development-kit#344]
The LDK is not supporting PING/PONG websocket functionality. I have a websocket server sending web socket messages with the PING message type and the websocket client in the LDK is not responding with a PONG message type. The websocket server closes the connection because it feels the connection is dead.

Please support PING/PONG. I don't know how necessary it is to provide something that allows the loop developer to support their own PONG implementation, but certainly having a default PONG implementation would be good.

**Comment by epiccoleman** [comment]
Hi Keith, and thanks for the feedback. This appears to be an oversight in our Websocket implementation as ping/pong is defined in the Websocket RFC.

We have created HELPS-1507 to add handling for these control frames, and will update this issue with relevant information. Thanks again for helping us put the LDK through its paces!

**Comment by KeithMHughesRoteraAI** [comment]
It would also be good to intercept the server ping message and send back one's own pong, and also just know the server is pinging so that the client would know if it needs to reinitiate a reconnect if the server dies and comes back online. I am using this for asynchronous messaging from the server, so there may or may not be many messages going from client to server.

**Comment by coltonbrugger** [comment]
Per today's call with OH Product Team, this is coming in V27. V27 is scheduled for tomorrow; if not completed/launched tomorrow, it will not come until after Thanksgiving.

**Comment by BrettMugglinOlive** [comment]
Released with LDK 3.7.0 and OH 0.27
