### ISSUE TITLE
layout.padding is not loved by the TextInput component

### ISSUE THREAD

**Issue by coltonbrugger** [open-olive/loop-development-kit#348]
Sample of using padding.

<img width="419" alt="Screen Shot 2021-09-14 at 4 08 19 PM" src="https://user-images.githubusercontent.com/1859587/133509960-c0420587-1566-40be-8394-a88ee305d170.png">

**Comment by epiccoleman** [comment]
Hi Colton. If you still have the code sample that produced this screenshot, could you share it with us? It will help us with reproducing this behavior.

In the meantime, we've created HELPS-1519 to address this bug. We'll update this ticket with any relevant information. Thanks for your feedback!

**Comment by coltonbrugger** [comment]
Here is the code for inputs 2 through 4 shown in [screenshot](https://user-images.githubusercontent.com/1859587/133509960-c0420587-1566-40be-8394-a88ee305d170.png).

```
const textInput2a: whisper.TextInput = {
  type: whisper.WhisperComponentType.TextInput,
  label: 'Text Input 2 (padding-small)',
  onChange: (_error: Error | undefined, val: string) => {
    console.log('Text changed: ', val);
  },
  layout: {
    paddingTop: StyleSize.Small,
    paddingBottom: StyleSize.Small,
  },
};
const textInput3a: whisper.TextInput = {
  type: whisper.WhisperComponentType.TextInput,
  label: 'Text Input 3 (padding-medium)',
  onChange: (_error: Error | undefined, val: string) => {
    console.log('Text changed: ', val);
  },
  layout: {
    paddingTop: StyleSize.Medium,
    paddingBottom: StyleSize.Medium,
  },
};
const textInput4a: whisper.TextInput = {
  type: whisper.WhisperComponentType.TextInput,
  label: 'Text Input 4 (padding-large)',
  onChange: (_error: Error | undefined, val: string) => {
    console.log('Text changed: ', val);
  },
  layout: {
    paddingTop: StyleSize.Large,
    paddingBottom: StyleSize.Large,
  },
};
```

**Comment by epiccoleman** [comment]
Thanks for posting this, Colton - I've added it to our issue description to aid in reproduction.
