### ISSUE TITLE
CollapseBox opens to the top.

### ISSUE THREAD

**Issue by cgeleta620** [open-olive/loop-development-kit#352]
Can we have the collpaseBox open to the top?

Current action:

<img width="357" alt="Screen Shot 2021-09-16 at 11 48 55 AM" src="https://user-images.githubusercontent.com/16765849/133644208-04f28a94-4da2-4c4c-a5ac-1b40953fefab.png">
<img width="360" alt="Screen Shot 2021-09-16 at 11 49 05 AM" src="https://user-images.githubusercontent.com/16765849/133644218-ee8b084f-c55e-4b8d-87df-b2d0f5d38d97.png">

Desired action:

![image-2021-08-25-14-48-06-944](https://user-images.githubusercontent.com/16765849/133644368-221a74db-cad5-4afa-981e-25a881f36531.png)
![image-2021-08-25-14-49-11-619](https://user-images.githubusercontent.com/16765849/133644372-b9e78976-39f6-4b3b-8f58-d3a149e698ec.png)

**Comment by epiccoleman** [comment]
Hi @cgeleta620 ! We've created HELPS-1520 to track this feature request. We'll update this ticket with any relevant information. 

Thanks for your feedback!

**Comment by BrettMugglinOlive** [comment]
HELPS-1520 was released a couple versions ago, and should have provided the requested functionality!
