### ISSUE TITLE
Absolute path version of filesystem.join

### ISSUE THREAD

**Issue by dannyAtOlive** [open-olive/loop-development-kit#353]
Scenario: need to write an html file and open it using the default browser. We can write the file just fine, but the link component needs an absolute path to find the file. We can't predict the name of the relative directory the loop operates in (for example, 95ddfae9-3bd0-41d0-9b4c-aff1574dc487) and it looks like we can't write files outside this environment.

**Comment by cshields-oliveai** [comment]
Hello @dannyAtOlive. Within Olive Helps, there is the concept of a "Loop working directory". Here is some documentation pertaining to this feature:

Each Loop gets a dedicated working directory that it can use to store files that don't need to be placed in a specific location. 

Other Loops will not be able to access this directory.

Each Loop with filesystem permissions requested will automatically have access to this directory, its subdirectories, and any files within. If you only need access to the working directory, provide an empty `filesystem` permissions object:

```json
{
  "ldk": {
    "permissions": {
      "filesystem": {}
    }
  }
}
```

To access a file or directory inside the working directory, provide a relative path:
```js
const csvContents = await ldk.filesystem.readFile('./my-file.csv');
```

- Loops can do whatever they want in this directory, but they cannot destroy their working directory. For example `filesystem.remove("./")` will fail.
- All relative paths are automatically allowed as long as they actually resolve to something in the Loop's "work directory".
- File paths which refer to parent directories (example: `../`) requires permissions to be specifically provided as normal.
- Shutting down or updating a Loop does not delete the working directory or its contents.


In the example you described, perhaps you can write your html file and recall it from the Loop's working directory. Will this suffice to achieve what you are attempting to do?

Let us know.

**Comment by dannyAtOlive** [comment]
I was trying to use the link component but I haven't been able to get it to work with the relative path. I thought it needed the absolute path. What format should the link string be in to find the file? Or is there a way to avoid the link and just do openFile(path")?

**Comment by epiccoleman** [comment]
Hi Danny. I was able to get an example working that I think does what you're attempting. This is a small loop which writes an html file to the filesystem and then produces a Whisper with a Link component. The link component's target is a `file://` type link which opens the HTML file in the browser when clicked. 

I believe there are some limitations of opening HTML with the `file://` link type, so you may need to do some testing around your particular use case to see if this would work for you. You would also most likely want to change the path of the file in question.

Another critical part of making this approach work is to declare the correct permissions in your Loop's package.json - I've attached the relevant section of that config at the bottom of this comment after the code. 

Let me know if this approach gets you what you need. If this is too limiting, we may be able to add a helper for getting the absolute path of the Loop's working directory or similar.

### main loop file
```
import { whisper, filesystem } from '@oliveai/ldk';

const main = () => {
  filesystem.writeFile({
    data: "hello world",
    path: "/Users/epiccoleman/src/test.html",
    writeMode: 600,
    writeOperation: 
  })

  whisper.create({
    label: 'Link',
    onClose: () => {},
    components: [
      {
        type: whisper.WhisperComponentType.Link,
        text: "test",
        href: "file:///Users/epiccoleman/src/test.html"
      }
    ]
  });
};

main();
```

### ldk config in `package.json`
```
"ldk": {
    "permissions": {
      "clipboard": {},
      "whisper": {},
      "filesystem": {
        "pathGlobs": [

        {
          "value": "/Users/ericcoleman/src/test.html"
        }
        ]
      }
    }
  },
```

**Comment by dannyAtOlive** [comment]
That worked, but I think there are a couple issues when publishing this for users.

* The working directory is safe regarding permissions to write, but could stricter systems cause a problem when writing outside it like in this example?
* Also, the path would change depending on OS, but I imagine that's one of the easier things to solve.
* The biggest problem I see is this approach requires the file name to be included in the permissions. The loop we're working on sends a request for CPT requirements based on code and payer name. The file would be something like "27447 BCBS MINNESOTA.html" for that code/payer combination. The name could be made to be the same for all requests, but then users wouldn't get to click on old links if those whispers are still open. It isn't much to send a new request but it may be an odd user experience to have an outdated whisper/link on screen.

**Comment by dannyAtOlive** [comment]
The third bullet point is no longer a concern. I've left you a Slack with more detail @epiccoleman
