### ISSUE TITLE
VSCode: Error Creating Loop - Path contains invalid characters

### ISSUE THREAD

**Issue by trevorboardman** [open-olive/loop-development-kit#354]
When running the command `Create Loop` and browsing for a folder, an error is shown: `Error creating loop: Path contains invalid characters: /C:/Loops/FirstLoop`
Manually removing the first `/` allows me to create the loop project successfully. 
![image](https://user-images.githubusercontent.com/35644929/134110290-832b44f1-2f10-4468-8c60-c69533cf9464.png)

OS: Win 10 20H2
LDK Extension Version: v0.1.12
LDK Version: 3.2.0
Olive Helps: 0.23.2

**Comment by CandiceCLB** [comment]
Hi, Trevor. Our technical team will look at this when they get online for the day but I do notice the version of LDK you're using is a few versions old. The most current version is LDK V3.3.0- you may want to update to the latest and greatest version to see if that will help.

**Comment by trevorboardman** [comment]
HI @CandiceCLB thanks for looking into this! 

When I look in VSCode, v0.1.12 is the latest version of the LDK extension
![image](https://user-images.githubusercontent.com/35644929/134206383-330e1399-71a1-467e-98e6-3abdb88eea43.png)

In the dev docs for Helps, it says to get the LDK by installing the extension via VSCode. https://docs.oliveai.dev/ldk/your-first-loop/creating-a-loop

**Comment by trevorboardman** [comment]
I should have clarified the versioning in my initial post. The LDK version is 3.2.0
![image](https://user-images.githubusercontent.com/35644929/134206880-d517f649-2d2c-474d-b141-785090706a34.png)
And the extension version is v.0.1.12. Sorry!
