### ISSUE TITLE
Link component's onClick attribute takes over

### ISSUE THREAD

**Issue by dannyAtOlive** [open-olive/loop-development-kit#363]
The default intro whisper and my own loop both exhibit the same behavior. When a link component is given an href, it opens it just fine. When it's given an onClick callback, it executes it just fine. When it's given both, it only executes the callback. Can it be updated so both actions launch?

**Comment by RusGraf** [comment]
Hello @dannyAtOlive, thank you for reporting this behavior. It looks like this is a known problem and fix for this feature is already in the works. It will be released with the next version release (for the reference here is the LDK story card associated with the fix: HELPS-1352).
