### ISSUE TITLE
Dual login shares resources / state

### ISSUE THREAD

**Issue by kingofclarkston** [open-olive/loop-development-kit#364]
When I log in with a second user on the same machine, the loops that were active for the first user are opened. This raises concerns for state being shared across logins.

**Comment by DanielWagersOlive** [comment]
Hi @kingofclarkston!  Thanks for calling this out.  This is definitely on our radar, and we have a ticket in our backlog to have Loop installation data segregated by login.  (HELPS-344)  There's an ongoing discussion happening right now about how and when this will be addressed.  We'll update this issue when we know more.

**Comment by BrettMugglinOlive** [comment]
Updating ticket number to HELPS-1354

**Comment by MaggieMaSS** [comment]
This issue has been fixed on Olive Helps 0.36.3.
