### ISSUE TITLE
CollapseBox applies hover styles to child Box components when an `onClick` handler is attached

### ISSUE THREAD

**Issue by kevinfiol** [open-olive/loop-development-kit#370]
I noticed this issue when trying to dynamically apply the label of a `CollapseBox` component upon the user clicking on the "more" button. If I remove the `onClick` handler from the `CollapseBox` below, the gray background hover style does not apply.

**Olive LDK Version:** 3.3.0, although I briefly tested 3.4.0-beta.1 and the issue was still present.

**Steps to reproduce:**
1. Create a new whisper
2. Paste the following code:
```js
const { whisper } = require('@oliveai/ldk');

whisper.create({
  label: 'Hello world',
  components: [
    {
      type: whisper.WhisperComponentType.CollapseBox,
      open: false,
      // This onClick handler somehow triggers bg hover styles to the Box component below
      onClick: () => {
        console.log('foo');
      },
      children: [
        {
          type: whisper.WhisperComponentType.Markdown,
          body: '# this is fine'
        },
        // The component below has hover styles applied to it
        {
          type: whisper.WhisperComponentType.Box,
          direction: whisper.Direction.Vertical,
          justifyContent: whisper.JustifyContent.Left,
          children: [
            {
              type: whisper.WhisperComponentType.Markdown,
              body: '# this is not fine'
            }
          ]
        }
      ]
    }
  ]
});
```

**Screenshot:**

![2021-09-29_10-28](https://user-images.githubusercontent.com/4752973/135289337-433bad4a-1b39-4666-a1cf-5677b3ac3212.png)

**Comment by DanielWagersOlive** [comment]
Hi @kevinfiol!  Thank you for bringing this issue to our attention.  We'll get back to you when we have a fix in place.

**Comment by coltonbrugger** [comment]
Coming in V27 (tomorrow or right after Thanksgiving), per today's call.

**Comment by BrettMugglinOlive** [comment]
Fixed by HELPS-1702
