### ISSUE TITLE
[Feature Request] Add onHover to WhisperComponentType.Link

### ISSUE THREAD

**Issue by kingofclarkston** [open-olive/loop-development-kit#372]

**Comment by MaggieMaSS** [comment]
Hey @kingofclarkston, thanks for the feedback! 

We've created HELPS-1699 evaluate this suggestion and will talk to our product owner about this feature request and update this ticket accordingly. Thanks for bringing this to our attention.

**Comment by MaggieMaSS** [comment]
Hey @kingofclarkston, could you please provide more details for us? What methods/functions do you want to trigger when the link is  onHover?

**Comment by kingofclarkston** [comment]
@MaggieMaSS we are looking for the link to be underlined when hovering as shown in the Olive design docs. 
<img width="850" alt="Screen Shot 2021-11-29 at 6 09 11 AM" src="https://user-images.githubusercontent.com/62415389/143883202-3c9d50b8-993e-43f4-876e-f4dfe7a4b29b.png">

**Comment by MaggieMaSS** [comment]
@kingofclarkston  This feature has been released in Olive Helps 0.36.3 so I'll go ahead and close this issue! We really appreciate your feedback! Thanks!
