### ISSUE TITLE
React whispers don't compile using nested children 

### ISSUE THREAD

**Issue by latman-oliveai** [open-olive/loop-development-kit#376]
TS version: 4.2.4

![image](https://user-images.githubusercontent.com/83671673/136276770-79766896-8719-4da7-88fd-dc7156d7f36a.png)

This does not work:
```
    <oh-whisper label="Medical Records Request" onClose={() => {}}>
      <>
        <oh-markdown body={miette} />
        <oh-button
          onClick={() => {
            updateCount(count + 1);
          }}
          label="Another year of jail for Mother!"
        />
      </>
    </oh-whisper>
```
Build error:
> [tsl] ERROR in /Users/michaellatman/dev/magenta/src/whispers/KeyboardWhisper.tsx(16,6)
>       TS2741: Property 'children' is missing in type '{ label: string; onClose: () => void; }' but required in type 'WhisperProps'.
> 

Currently, we must do this:
```
  return (
    <oh-whisper
      label="Medical Records Request"
      onClose={() => {}}
      children={
        <>
          <oh-markdown body={miette} />
          <oh-button
            onClick={() => {
              updateCount(count + 1);
            }}
            label="Another year of jail for Mother!"
          />
        </>
      }
    />
  );
```

**Comment by BrettMugglinOlive** [comment]
I believe that this behavior ended up just being an environment set up issue. We have better documentation for how to get JSX components working located [here](https://docs.oliveai.dev/aptitudes/whisper/jsx-whispers) in our dev hub documentation. Hope that helps!

I'm going to go ahead and close this thread. If you still think there is an issue, please reopen it and we'll look further!
