### ISSUE TITLE
ScrollBar showing for Box component when no customHeight set

### ISSUE THREAD

**Issue by jjnistico** [open-olive/loop-development-kit#380]
ldk version: 3.4.0
helps version: 0.24.6

When creating a box component, a scrollbar is shown even without setting a customHeight. I have only tested/noticed this with a `Select` component inside a box.

```
const housingTypeDropdown: whisper.Select = {
    type: whisper.WhisperComponentType.Select,
    id: 'housingResourceType',
    key: 'housingResourceType',
    label: 'Housing Resource',
    options: [
      'Housing Financial Assistance',
      'Temporary Shelter',
      'Subsidized Rentals (Section 8)',
    ],
    selected: 0, // housingTypeIndex(housingResourcesWhisper.getState('housingType')),
    onSelect: async (_, param) => {
      // removed state management for repro
      // housingResourcesWhisper.resetState();
      // housingResourcesWhisper.setState('housingType', indexToHousingType(param), true);
    },
  };

  const paddedDropdown: whisper.Box = {
    type: whisper.WhisperComponentType.Box,
    justifyContent: JustifyContent.Left,
    direction: Direction.Vertical,
    children: [housingTypeDropdown],
    layout: {
      marginTop: StyleSize.Small,
    },
  };
```

![image](https://user-images.githubusercontent.com/22761318/136601335-6792c77b-a039-4b1d-9baa-8866acce96c9.png)

**Comment by coltonbrugger** [comment]
New evolution of this bug. It actually appears that the element can scroll partially out of view (see loss of top border on input).

See screenshot below.

<img width="647" alt="Screen Shot 2021-11-18 at 8 54 13 AM" src="https://user-images.githubusercontent.com/1859587/142464002-67e4d373-d743-4ef0-846a-1ffdc434a3c0.png">

**Comment by coltonbrugger** [comment]
Coming in V27 (tomorrow or right after Thanksgiving), per today's call.
