### ISSUE TITLE
Markdown Hyperlinks have CSS `top` property and messes up text alignment

### ISSUE THREAD

**Issue by kevinfiol** [open-olive/loop-development-kit#382]
LDK Version: 3.4.0

Defining hyperlinks in a Markdown component's body causes weird alignment issues. The issues are exacerbated when bolding the hyperlink. See screenshots below. I reproduced this to confirm using the code below:

```ts
const { whisper } = require('@oliveai/ldk');

whisper.create({
  label: 'Hello world',
  onClose: () => {},
  components: [
    {
      type: whisper.WhisperComponentType.Markdown,
      body: 'Source: [Link](https://circulohealth.com)'
    },
    {
      type: whisper.WhisperComponentType.Box,
      direction: whisper.Direction.Vertical,
      justifyContent: whisper.JustifyContent.Left,
      children: [
        {
          type: whisper.WhisperComponentType.Markdown,
          body: 'Source: [Link](https://circulohealth.com)'
        },
        {
          type: whisper.WhisperComponentType.Markdown,
          body: 'Source: **[Link](https://circulohealth.com)**'
        }
      ]
    }
  ]
});
```

![2021-10-11_15-51](https://user-images.githubusercontent.com/4752973/136848809-c02a573d-11ad-46ca-ab92-25e305335df1.png)
![2021-10-11_16-03](https://user-images.githubusercontent.com/4752973/136849035-eb41cda4-6e81-4f59-bec3-70f198642871.png)

**Comment by cshields-oliveai** [comment]
Hello @kevinfiol, thanks for the thorough reporting on this one. Upon initial inspection, that does not seem to be the intended behavior. I will take this back to the team and we will let you know as soon as we have an update for you.

**Comment by coltonbrugger** [comment]
Coming in V27 (tomorrow or right after Thanksgiving), per today's call.

**Comment by BrettMugglinOlive** [comment]
Fixed by HELPS-1795
