### ISSUE TITLE
Icons get extra padding on bottom within a div

### ISSUE THREAD

**Issue by kyuhas** [open-olive/loop-development-kit#394]
I added an icon to my whisper and the span doesn't have any padding, but the div that contains the span does. This prevents me from being able to vertically align an icon and text to the center. 

For example, see the code and output below:
```
export const MyComponentTestingAlignment = (props) => {
  return (
    <oh-box
      justifyContent={JustifyContent.Left}
      direction={Direction.Horizontal}
      alignItems={AlignItems.Center}
      layout={{ padding: StyleSize.None, margin: StyleSize.None }}
    >
      <oh-icon
        color={Color.WhisperStrip}
        name={'fiber_new'}
        size={IconSize.Large}
      />
      <oh-markdown body={`testing`} />
    </oh-box>
  );
};
```
<img width="377" alt="Screen Shot 2021-10-20 at 4 52 53 PM" src="https://user-images.githubusercontent.com/26147799/138170518-43dcda00-f713-4087-b3fa-12b10b51ff65.png">

Is this something that can be fixed? Thanks!

**Comment by mattbee-olive** [comment]
still backlogged @kyuhas

**Comment by BrettMugglinOlive** [comment]
This bugfix has been released! Closing the thread out.
