### ISSUE TITLE
[Feature Request] Add an equivalent to `element.scrollTo` to programmatically scroll within a Whisper

### ISSUE THREAD

**Issue by kevinfiol** [open-olive/loop-development-kit#406]
Following up from a brief discussion we had on Slack. :+1: 

This feature would be very useful in cases where we would like to refocus on a particular component inside a whisper. I discovered the need for this while working on a pagination component, where it would improve the UX to be able to refocus to the top of the results once the user navigated to the next page.

MDN: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo

Let me know if I can clarify anything else. :smiley_cat:

**Comment by BrettMugglinOlive** [comment]
Thanks for the suggestion! WE opened up HELPS-2101 to track this work. We'll let you know if we need any additional feedback!

**Comment by MaggieMaSS** [comment]
Hey @kevinfiol,  we're closing this out since we cannot do this request.

**Comment by stefanmillerolive** [comment]
Thank you for your submission. After reviewing with the team, this is not something that we can provide at this time.
