### ISSUE TITLE
Box component hover style with children

### ISSUE THREAD

**Issue by AlyseTack** [open-olive/loop-development-kit#408]
![image](https://user-images.githubusercontent.com/14366837/140436791-80e4796f-b7b2-459a-8359-80d8e43eb201.png)
The hover style is showing the white background in patches if there are nested child components.  From a quick look in the dev tools it looks like an issue with the scrollbar (::-webkit-scrollbar-track) having a background and border it might be fixed with removing a scrollbar when it's not needed. Removing these two properties fixes the issue:
![image](https://user-images.githubusercontent.com/14366837/140437867-09a35655-b683-4b1b-990a-eaa290d3af8c.png)

Here is our code that reproduces the behavior:
`<oh-box
      direction={Direction.Vertical}
      justifyContent={JustifyContent.Left}
      key={`single-pat-not-box-${itemNumber}`}
    >
      <oh-box
      key="patient-notif-summary-with-date"
      direction={Direction.Horizontal}
      justifyContent={JustifyContent.SpaceBetween}
      onClick={() => {
        patNot.noLongerNew();
        dispatch(updatePatientNotificationLite(patNot));
        dispatch(updatePage(Page.NOTIFICATION_DETAILS));
      }}
    >
      <oh-box
        key="patient-notif-summary"
        direction={Direction.Vertical}
        justifyContent={JustifyContent.Left}
        layout={{ marginTop: StyleSize.Small, marginBottom: StyleSize.Medium }}
      >
        <oh-box
          key="patient-name-and-icon-box"
          direction={Direction.Horizontal}
          justifyContent={JustifyContent.Left}
          layout={{ padding: StyleSize.None, margin: StyleSize.None }}
          alignItems={AlignItems.Center}
        >
          {getNewIcon(patNot)}
          <oh-box
            key="patient-name-box"
            direction={Direction.Horizontal}
            justifyContent={JustifyContent.Left}
            layout={{ padding: StyleSize.None, margin: StyleSize.None }}
          >
            <oh-markdown body={`**${patNot.patientInfo.getPatientName()}**`} key="patient-name" />
          </oh-box>
        </oh-box>
        <oh-markdown
          key="patient-dx-visit-type"
          body={`
Primary DX: ${removeDiagnosisCode(patNot.visitDetails.primaryDx)}  
${patNot.visitDetails.visitType}`}
        />
        {getLabel(patNot)}
      </oh-box>
      <oh-box
        key="patient-notif-date-box"
        direction={Direction.Vertical}
        justifyContent={JustifyContent.Right}
        layout={{ marginTop: StyleSize.Small, marginBottom: StyleSize.Medium }}
        alignItems={AlignItems.FlexEnd}
      >
        <oh-markdown body={`${formatDate(patNot.notificationDate)}`} key="patient-notif-date" />
      </oh-box>
    </oh-box>
      <oh-divider key={`single-pat-not-div-${itemNumber}`} />
    </oh-box>`

**Comment by BrettMugglinOlive** [comment]
Thanks for bringing this to our attention. I created HELPS-2107 to track this issue, and we'll let you know once it's addressed!

**Comment by AlyseTack** [comment]
@BrettMugglinOlive Do we have an estimated timeline for when this will be addressed?

**Comment by coltonbrugger** [comment]
Here is additional video showing the unfortunate effect this bug has on the interface.

Since we cannot get rid of the white borders within, nor can we control whether the hover background shows, we are simply stuck with this.

We will not be able to launch this Provider Workflow demo loop until this bug is fixed. We are near completion of V1.

https://user-images.githubusercontent.com/1859587/142056145-2d49e95c-d43c-4114-a198-d4a01e7956db.mov

**Comment by BrettMugglinOlive** [comment]
@AlyseTack @coltonbrugger Unfortunately, it doesn't look like this defect made it in for the release that will be coming out here in the next week or so, but I can try to get it prioritized to be addressed next.

**Comment by mimoduo** [comment]
@AlyseTack @coltonbrugger Heya! I'm currently investigating this bug but was unable to render the whisper correctly. If possible can you provide the full component file that resulted in the described behavior? That'll help make sure we can really knock this sucker out!

PS: Using 3 backticks followed by code and another 3 backticks formats everything perfectly ;)

```
// imports

// const Component

// export Component
```

**Comment by AlyseTack** [comment]
In order to reproduce this, you can just have a box component with two other boxes inside that have direction horizontal.  You can then add an onClick function to the outer box to produce the hover.  Youll notice that the more boxes you nest inside the children, the more white blocks appear on hover.  Here is the layout we are using.  There are some function in this code you would have to remove in order to get this to work completely on your end

```
    <oh-box
      key="patient-notif-summary-with-date"
      direction={Direction.Horizontal}
      justifyContent={JustifyContent.SpaceBetween}
      onClick={() => {
        patNot.noLongerNew();
        dispatch(updatePatientNotificationLite(patNot));
        dispatch(updatePage(Page.NOTIFICATION_DETAILS));
      }}
    >
      <oh-box
        key="patient-notif-summary"
        direction={Direction.Vertical}
        justifyContent={JustifyContent.Left}
        layout={{ marginTop: StyleSize.Small, marginBottom: StyleSize.Medium}}
      >
        <oh-box
          key="patient-name-and-icon-box"
          direction={Direction.Horizontal}
          justifyContent={JustifyContent.Left}
          layout={{ padding: StyleSize.None, margin: StyleSize.None }}
          alignItems={AlignItems.Center}
        >
          {getNewIcon(patNot)}
          <oh-box
            key="patient-name-box"
            direction={Direction.Horizontal}
            justifyContent={JustifyContent.Left}
            layout={{ padding: StyleSize.None, margin: StyleSize.None }}
          >
            <oh-markdown body={`**${patNot.patientInfo.getPatientName()}**`} key="patient-name" />
          </oh-box>
        </oh-box>
        <oh-markdown
          key="patient-dx-visit-type"
          body={`
Primary DX: ${patNot.visitDetails.primaryDx}  
${patNot.visitDetails.visitType}`}
        />
        {getLabel(patNot)}
      </oh-box>
      <oh-box
        key="patient-notif-date-box"
        direction={Direction.Vertical}
        justifyContent={JustifyContent.Right}
        layout={{ marginTop: StyleSize.Small, marginBottom: StyleSize.Medium }}
        alignItems={AlignItems.FlexEnd}
      >
        <oh-markdown body={`${formatDate(patNot.notificationDate)}`} key="patient-notif-date" />
      </oh-box>
    </oh-box>
    ```

**Comment by mimoduo** [comment]
Shucks that was a fast reply @AlyseTack thank you so much, this is exactly what we're looking for!

**Comment by BrettMugglinOlive** [comment]
This bugfix has been released! Closing this thread
