### ISSUE TITLE
Default of select dropdown inside collapse box creates scrollbar

### ISSUE THREAD

**Issue by AlyseTack** [open-olive/loop-development-kit#410]
A scrollbar appears if we add a select dropdown to a box component.  In this example, each dropdown is in it's own box so we can space them vertically and you can see three separate scroll bars.  When they were all in one box, there was a large grey scrollbar the full length of the box.

Example:
![image](https://user-images.githubusercontent.com/14366837/140438765-9179e3f2-1558-48f1-bfc4-4b2fb4cdc6c7.png)

**Comment by AlyseTack** [comment]
Just noticed this is a duplicate of issue #380

**Comment by BrettMugglinOlive** [comment]
This issue you referenced is being worked on, and should hopefully make it in the next release. But, I think you might be able to accomplish what you're trying to do without having to rely on using all those Boxes!

If you're trying to add some space between the Select components vertically, you should use the `layout` property! Its purpose is to give developers a way to fine tune positioning of elements, and exposes properties like `margin` and `padding`. Plus, it's found on every single component! In this case, if you're trying to add some vertical spacing between the elements, remove the components from the Boxes and add something like `layout: { marginTop: StyleSize.Medium }` to each Select components, and that should remove those scroll bars!

Let me know if that solves your problem.

**Comment by AlyseTack** [comment]
Yup that fixed it! Thanks!
