### ISSUE TITLE
Autocomplete with multiple selections has overflow

### ISSUE THREAD

**Issue by AlyseTack** [open-olive/loop-development-kit#414]
While using the autocomplete component, if we allow multiple selections, the UI displays the selections outside of the select box.

Example:
![image](https://user-images.githubusercontent.com/14366837/140589492-f99c3c63-b103-44b8-b894-ed3700e18847.png)

**Comment by MaggieMaSS** [comment]
Thanks for the feedback! @AlyseTack I think it's gonna be the same code as issue#414 Autocomplete with multiple selections has overflow. But could you please send us sample code you used if there's any different code you wrote?
Thanks!

**Comment by AlyseTack** [comment]
Hi @MaggieMaSS  I posted the code snippet in the workflow-olive chat but I'll do the same here.  The overflow issue I created was more about the fact that the selected options were shown outside of the text box while this one is physically returning the array of selections with duplicates because it's allowing a user to select something that is already selected since the dropdown is clearing out the selected checkboxes.

Here's the code I used to produce it.  You have to click around a couple times.  I haven't figured out the exact pattern but I've had it happen by having all the options selected and then selecting and unselecting the last option.  I've been able to reproduce it a few times.
```
      <oh-autocomplete
        label="Visit Type"
        multiple={true}
        options={[{
          label: "Hospital Discharge",
          value: "0"
        },{
          label: "Behavioral Health Visit",
          value: "1"
        },{
          label: "ED Visit",
          value: "2"
        },{
          label: "Substance Use Visit",
          value: "3"
        }]}
        onSelect={(_, val) => {console.log(val)}}
        layout={{
          marginBottom: StyleSize.Medium,
        }}
      />

```

**Comment by AlyseTack** [comment]
This is happening with the same component configuration as the previous issue.  I created them as separate issues since this one is specifically pointing out the visual overflow that is on the screen with the selections not inside the text box while the other one is more of a usability issue where the dropdown is clearing out the selected options on occasion and allowing a user to select an already selected option.  

Here's the config:

```
<oh-autocomplete
  label="Visit Type"
  multiple={true}
  options={[{
    label: "Hospital Discharge",
    value: "0"
  },{
    label: "Behavioral Health Visit",
    value: "1"
  },{
    label: "ED Visit",
    value: "2"
  },{
    label: "Substance Use Visit",
    value: "3"
  }]}
  onSelect={(_, val) => {console.log(val)}}
  layout={{
    marginBottom: StyleSize.Medium,
  }}
/>
```

**Comment by MaggieMaSS** [comment]
@AlyseTack  Thanks for the code snippet! We have created HELPS-2160 to further for this issue. We'll let you know when it's fixed! Thanks!

**Comment by BrettMugglinOlive** [comment]
This bugfix has been released! Closing this thread.
