### ISSUE TITLE
Autocomplete allowing a user to select the same option multiple times

### ISSUE THREAD

**Issue by AlyseTack** [open-olive/loop-development-kit#415]
In the autocomplete component you are able to select the same option multiple times and it simply appends that option to the list shown.  

Reproducing steps:
I selected 3 of the 4 available options in the dropdown, closed the dropdown, reopened it, unselected an option, closed the dropdown, and then when I reopened the dropdown it says that nothing is selected.  If you then go through and make a few selections and close the dropdown it will show more options than are possible as being selected.

In this example, I only have 4 items in the dropdown:
![image](https://user-images.githubusercontent.com/14366837/140590035-ba57f90d-9c48-4586-9732-355c4bef19ce.png)

**Comment by MaggieMaSS** [comment]
Thanks for the feedback! @AlyseTack  Could you please send us some sample code for investigation? Thanks!

**Comment by AlyseTack** [comment]
Hi @MaggieMaSS I posted the code snippet in the workflow-olive chat but I'll do the same here. In this issue the component is physically returning the array of selections with duplicates because it's allowing a user to select something that is already selected since the dropdown is clearing out the selected checkboxes if you click around enough.

Here's the code I used to produce it. You have to click around a couple times. I haven't figured out the exact pattern but I've had it happen by having all the options selected, closing the dropdown, reopening the dropdown, and then selecting and unselecting the last option. I've been able to reproduce it a few times.

```
      <oh-autocomplete
        label="Visit Type"
        multiple={true}
        options={[{
          label: "Hospital Discharge",
          value: "0"
        },{
          label: "Behavioral Health Visit",
          value: "1"
        },{
          label: "ED Visit",
          value: "2"
        },{
          label: "Substance Use Visit",
          value: "3"
        }]}
        onSelect={(_, val) => {console.log(val)}}
        layout={{
          marginBottom: StyleSize.Medium,
        }}
      />
```

**Comment by MaggieMaSS** [comment]
@AlyseTack  Thanks for your detailed description and code snippet! We have created HELPS-2161 to address this issue, and we'll keep you updated! Thanks!

**Comment by mattbee-olive** [comment]
this is getting tested on qa @AlyseTack

**Comment by BrettMugglinOlive** [comment]
This bugfix has been released! Closing the thread

**Comment by AlyseTack** [comment]
Thank you for the update!!
