### ISSUE TITLE
Add ability to disable automatic formatting of email addresses within markdown/message components

### ISSUE THREAD

**Issue by kyuhas** [open-olive/loop-development-kit#417]
Hi all, I am trying to display an email address within one of my whispers and instead of just displaying the email as plain text, which is what I am hoping to have, it creates an icon to the left of the email address and converts the email address to a clickable link. See code and screenshot attached below.

Is there a way to disable this automatic formatting somehow so that I can just display it as plain text? (Note: this also happens when you use a message component as well).

```
import { Direction, JustifyContent } from '@oliveai/ldk/dist/whisper';
import React from 'react';

export const TestEmailMarkdown = () => {
  return (
    <oh-box direction={Direction.Vertical} justifyContent={JustifyContent.Left}>
      <oh-markdown body="thisisabug@testingolivecomponents.com" />
    </oh-box>
  );
};
```

<img width="311" alt="Screen Shot 2021-11-09 at 11 47 04 AM" src="https://user-images.githubusercontent.com/26147799/140967684-adc504f8-8f2a-437e-9edd-49ccd51dab2c.png">

**Comment by MaggieMaSS** [comment]
@kyuhas Thanks for the feedback! There're several discussions inside OliveHelps team regarding this feature. We'll keep you updated!

**Comment by MaggieMaSS** [comment]
We have created a ticket to better address this issue. We'll let you know once it's done! Thanks!

**Comment by BrettMugglinOlive** [comment]
@kyuhas We have made a fix to remove the icon that appears, but it doesn't look like it was possible to disable auto-linking emails within `Markdown` components. 

I'm going to close this for now, but if you feel you need a solution to the autolinking, feel free to comment and reopen this!
