### ISSUE TITLE
Lots of options in select component displays across entire height of Olive Helps app

### ISSUE THREAD

**Issue by kyuhas** [open-olive/loop-development-kit#419]
Hi all. If I have a select component with a ton of options (see image below), when I click on the dropdown, the overlay that appears takes up the entire height of the Olive Helps app. 

<img width="380" alt="SelectComponentManyOptions" src="https://user-images.githubusercontent.com/26147799/141185281-ef3bcd0f-4bd5-47f3-97ba-8dc944e510a5.png">

Is it possible to:
1) provide a prop for the max number of options it will show (and allow you to scroll to see more)
2) if no max number is provided, make the overlay not extend past the whisper itself
3) make the top of the overlay pinned to the top of the select component (like it is when there are a smaller number of options)

Thanks!

**Comment by MaggieMaSS** [comment]
Hey @kyuhas , thanks for your feedback! I have created a ticket to address this issue, we'll keep you updated! Thanks!

**Comment by JosefBud-olive** [comment]
Hey there, @kyuhas! Just wanted to let you know a fix for this is merged in and going through QA now. Should be arriving in an upcoming version.

**Comment by kyuhas** [comment]
@JosefBud-olive awesome, thank you for the update!

**Comment by BrettMugglinOlive** [comment]
This bugfix has been released! Closing this thread.
