### ISSUE TITLE
Setting WidthSize to Half reduces the div to a quarter width

### ISSUE THREAD

**Issue by AlyseTack** [open-olive/loop-development-kit#430]
I have a box component and inside are two boxes.  One is for the patient information and the other is for the date of the notification.  I was trying to get the patient information to only take up half of the available area in order to fix a wrapping problem with the date but noticed that setting the width to half actually reduced the content of the inner div to half of the whole div.  Setting width to half on the outermost box also squished all of the content to the left side only using about a quarter of the area.  

I've provided pictures for further explanation.

this is with the WidthSize set to half on the patient information:
![image](https://user-images.githubusercontent.com/14366837/142350296-cee78a40-9610-45fd-bb13-fa74cf98ae33.png)

Code for the above photo:
`    <oh-box
      key="patient-notif-summary-with-date"
      direction={Direction.Horizontal}
      justifyContent={JustifyContent.SpaceBetween}
      onClick={() => {
        patNot.noLongerNew();
        dispatch(updatePatientNotificationLite(patNot));
        dispatch(updatePage(Page.NOTIFICATION_DETAILS));
      }}
    >
      <oh-box
        key="patient-notif-summary"
        direction={Direction.Vertical}
        justifyContent={JustifyContent.Left}
        layout={{ marginTop: StyleSize.Small, marginBottom: StyleSize.Medium, width: WidthSize.Half }}
      >
        <oh-box
          key="patient-name-and-icon-box"
          direction={Direction.Horizontal}
          justifyContent={JustifyContent.Left}
          layout={{ padding: StyleSize.None, margin: StyleSize.None }}
          alignItems={AlignItems.Center}
        >
          {getNewIcon(patNot)}
          <oh-box
            key="patient-name-box"
            direction={Direction.Horizontal}
            justifyContent={JustifyContent.Left}
            layout={{ padding: StyleSize.None, margin: StyleSize.None }}
          >
            <oh-markdown body={`**${patNot.patientInfo.getPatientName()}**`} key="patient-name" />
          </oh-box>
        </oh-box>
        <oh-markdown
          key="patient-dx-visit-type"
          body={`
Primary DX: ${patNot.visitDetails.primaryDx}  
${patNot.visitDetails.visitType}`}
        />
        {getLabel(patNot)}
      </oh-box>
      <oh-box
        key="patient-notif-date-box"
        direction={Direction.Vertical}
        justifyContent={JustifyContent.Right}
        layout={{ marginTop: StyleSize.Small, marginBottom: StyleSize.Medium }}
        alignItems={AlignItems.FlexEnd}
      >
        <oh-markdown body={`${formatDate(patNot.notificationDate)}`} key="patient-notif-date" />
      </oh-box>
    </oh-box>`
    
Without the width size set:
![image](https://user-images.githubusercontent.com/14366837/142350525-013981e3-a7d5-47a8-8f0c-8ed50766ca49.png)

**Comment by MichaelOliveMcCarrick** [comment]
Taking a look!

**Comment by MichaelOliveMcCarrick** [comment]
Looks like a bug to me, created HELPS-2325 to track the issue

**Comment by AlyseTack** [comment]
Thanks!  Let me know if you would like me to repost the code to produce this.  I didn't realize it would format my code snippet so horribly and just learned how to post it properly here.

**Comment by MichaelOliveMcCarrick** [comment]
Managed to get it cleaned up pretty easily in vs code, so no worries! It helped a lot! We do have someone that picked up the card, and it looks like it's just shoving all the default margins on to the right of the component. So that first child box is taking up half the space.... but for some reason it has an 8 and 16 px margin to the right (for a total of 24 px margin taking up a quarter of the space).

**Comment by MaggieMaSS** [comment]
This issue has been fixed on Olive Helps 0.28.3.
