### ISSUE TITLE
More width sizing controls

### ISSUE THREAD

**Issue by AlyseTack** [open-olive/loop-development-kit#431]
We would like the ability to set a pixel width if we know something will always take up the same amount of space.  This is to alleviate some issues we are having with items wrapping when they technically have enough room on one line.  In my instance, I would like to set a width on my date on the right hand side of the whisper.

Here we have an issue where some date are wrapping when they shouldn't:
![image](https://user-images.githubusercontent.com/14366837/142350832-1fc02547-a61e-4d8f-8a86-098342f10ebb.png)

**Comment by MichaelOliveMcCarrick** [comment]
Thanks for the feedback! I've created HELPS-2322 to track this request.

**Comment by MaggieMaSS** [comment]
Hey @AlyseTack , after discussion, as we are using `rem` and `em` now, we don't have a plan to use pixels. I'll go ahead and close this issue ticket for now. Thanks!
