### ISSUE TITLE
Customize DropZone Text

### ISSUE THREAD

**Issue by MichaelOliveMcCarrick** [open-olive/loop-development-kit#432]
HELPS-2338
As a loop author, I'd like to have control over the DropZone text, including: Changing the display text prompting a user to drag and drop or browse to a file, the display text stating that the user has reached the maximum number of files, as well as the error messages in general (such as the unsupported file type and the error message when uploading more than the maximum allowed files).

**Comment by mattbee-olive** [comment]
This is on QA for testing

**Comment by MaggieMaSS** [comment]
This feature has been done and released in Olive Helps 0.30.2.
