### ISSUE TITLE
File Removed event on Drop Zone

### ISSUE THREAD

**Issue by MichaelOliveMcCarrick** [open-olive/loop-development-kit#434]
As a loop author, I'd like to have some way of knowing when a user removes a file from the drop zone component. An event fired off when a user deletes a file that was previously added to the drop zone would allow us to respond appropriately to changes.

**Comment by MichaelOliveMcCarrick** [comment]
HELPS-2341

**Comment by mattbee-olive** [comment]
On QA for testing

**Comment by MaggieMaSS** [comment]
This feature has been released on Olive Helps 0.28.3. :)
