### ISSUE TITLE
Olive Helps - Version 25.3 - "New Update Available" not working

### ISSUE THREAD

**Issue by terrancemacgregor** [open-olive/loop-development-kit#438]
From Loop Developer: "I opened up Olive Helps today and never saw the "New Update Available" thing come in (waited ~8 minutes). "

Expected outcome:  When opening Olive Helps, an update notification should happen automatically with simple instructions for a user to follow.

**Comment by MaggieMaSS** [comment]
@terrancemacgregor  Thanks for the feedback! You need to be an admin to get that update whisper. Would you mind to give it a try? :)

**Comment by BrettMugglinOlive** [comment]
Closing this, as this bug has been addressed in more updated versions of Olive Helps
