### ISSUE TITLE
v0.27.5: Local Loop runs in sidebar, but not shown in `Loop Authors > Local Loops` list

### ISSUE THREAD

**Issue by coltonbrugger** [open-olive/loop-development-kit#447]
I have a local loop that was installed in a previous version. In v0.27.5, the loop loads but does not display in my list of local loops.

See screenshot.

<img width="1622" alt="Screen Shot 2021-12-01 at 9 08 56 AM" src="https://user-images.githubusercontent.com/1859587/144260190-a567fb3b-ec09-4735-badb-0b5c83afd01c.png">

**Comment by BrettMugglinOlive** [comment]
This bugfix (HELPS-2469, since it wasn't listed) has been released! Closing this thread.
