### ISSUE TITLE
v0.27.5: Unable to install Loop from Loop Library

### ISSUE THREAD

**Issue by coltonbrugger** [open-olive/loop-development-kit#448]
In attempting to add v0.0.3 of Loop Studio from the Loop Library, I get the following error (text and screenshot provided):

```
Error invoking remote method 'message-loop/install': Error: unable to make request to core: not connected
```

<img width="1216" alt="Screen Shot 2021-12-01 at 9 07 56 AM" src="https://user-images.githubusercontent.com/1859587/144260518-3545e5eb-b3de-4dd7-8b8c-ee5cbfb4df06.png">

**Comment by brangi** [comment]
I am having a similar issue on the latest version - <img width="1331" alt="Screen Shot 2021-12-03 at 1 34 55 PM" src="https://user-images.githubusercontent.com/100468/144663140-911cff3b-96bb-4e4e-bc4c-5da50ed72cac.png">

**Comment by BrettMugglinOlive** [comment]
This bugfix (HELPS-2469, since it wasn't listed) has been released! Closing this thread.
