### ISSUE TITLE
v0.27.4 and v0.27.5: Numerous startup issues

### ISSUE THREAD

**Issue by coltonbrugger** [open-olive/loop-development-kit#449]
Saw numerous issues when starting up v0.27.4 this morning:

* `MuiBottomNavigation` div doesn't show up with Home + Sidenote + Loop Library buttons.
* Most items usually accessed with the `headerMenuButton` are not visible.
* Only way to access the Loop Library was to go to the View > Open Loop Library in application menu.

<img width="415" alt="Screen Shot 2021-12-01 at 9 06 27 AM" src="https://user-images.githubusercontent.com/1859587/144260829-dfdb3479-5425-42ad-b02d-1a6e52633276.png">
<img width="413" alt="Screen Shot 2021-12-01 at 9 06 49 AM" src="https://user-images.githubusercontent.com/1859587/144260833-cd0ecc57-f9c6-4106-b514-4f05ed1b35e6.png">
<img width="241" alt="Screen Shot 2021-12-01 at 9 06 59 AM" src="https://user-images.githubusercontent.com/1859587/144260834-b1d0e4e6-507f-42e0-807c-ec77281cd2eb.png">

FYI: My device has now been updated to v0.27.5, so I will not longer be able to repeat these on my machine.

**Comment by BrettMugglinOlive** [comment]
This bugfix (HELPS-2469, since it wasn't listed) has been released! Closing this thread.
