### ISSUE TITLE
Add a function to kill the OCR process in the Screen aptitude

### ISSUE THREAD

**Issue by JosefBud-olive** [open-olive/loop-development-kit#455]
"Is there any chance of a quick add to the Screen aptitude to Kill OCR? Our Olive Works loop is going to try to use OCR, but also trigger on clipboard (so if OCR fails and no whisper shows, the user is trained to copy text as a backup). We are worried that if OCR takes too long the user might have already copied text….then OCR might resolve and get duplicate whispers. We’d like to kill OCR as soon as the window changes - i.e., when Olive Helps becomes the active window."

**Comment by JosefBud-olive** [comment]
Test comment

**Comment by jeffsun-olive** [comment]
This issue has been resolved with the implementation of new [listenOCRMonitor](https://github.com/open-olive/loop-development-kit/blob/80079dbc3a01aa703c316a4e8df80b4066f0852b/ldk/javascript/src/screen/index.ts#L95) function
