### ISSUE TITLE
User Aptitude's Data

### ISSUE THREAD

**Issue by dannyAtOlive** [open-olive/loop-development-kit#458]
The user aptitude currently only gives us the email of the user. Can we request to include the full name and organization?

**Comment by fighthefire** [comment]
Hi, please include the Product Manager (Daren Barker) on how we can escalate this as an enhancement for Helps - this should be globally useful for all Loops and is critical for our endpoint to understand utilization data. Thank you!  -  Daren

**Comment by MaggieMaSS** [comment]
@dannyAtOlive Thanks for your feedback! I'd like to create a ticket to better address that. May I know what is your name? I want to schedule a quick meeting with @fighthefire  regarding that request. Thanks!

**Comment by fighthefire** [comment]
Danny Betancourt (Developer) and Daren Barker (Product Manager)

**Comment by MaggieMaSS** [comment]
Thanks for the info! I have create HELPS-2549 to address that! I'll DM you guys if we need to set up a meeting! Thanks!

**Comment by MaggieMaSS** [comment]
Thanks for your suggestion! This feature has been released in Olive Helps v0.32.0 :)
