### ISSUE TITLE
onClose is not called for react whispers

### ISSUE THREAD

**Issue by ssteuteville** [open-olive/loop-development-kit#473]
LDK: Version 3.9.0

The onClose handler is not being called for react whispers. Here is a very simple test that I set up:

```
    await ReactWhisper.renderNewWhisper(
      <oh-whisper label="test" onClose={() => console.log('closing whisper')}>
        <oh-markdown body="test" />
      </oh-whisper>,
    );
```

When I close the whisper, here is the output in logs:
```
021-12-29 10:40:37.872] [ui] [debug] sending tracking event
[2021-12-29 10:40:37.883] [ui] [debug] sending tracking event
[2021-12-29 10:40:37.000] [desktop-core] [debug] whisper closed interactionType=close whisperType=universal
[2021-12-29 10:40:58.000] [desktop-core] [debug] Sidenote core loop listener called
[2021-12-29 10:40:58.000] [desktop-core] [debug] matched 0 notes for keyword
[2021-12-29 10:40:58.000] [desktop-core] [debug] on-boarding loop clipboard listener called
[2021-12-29 10:40:58.475] [ui] [debug] sending tracking event
```

Using the same test without react, my log statement is just after
`[2021-12-29 10:40:37.000] [desktop-core] [debug] whisper closed interactionType=close whisperType=universal`

**Comment by ssteuteville** [comment]
the code is fairly abstract so I'm unsure without actually pulling it down, but I think I traced the bug down in WhisperRenderInstance
```
  private async createWhisper(whisperData: NewWhisper) {
    this.whisper = await create({ ...whisperData, onClose: this.handleOnClose });
    this.status = RenderInstanceStatus.Created;
  }
```
That method sets onClose in the NewWhisper config to this.handleClose which does call this.onCloseHandler?.(); but the only place onCloseHandler is set is in WhisperInstanceWrapper's constructor, and it's set to just do this:
```
  handleWhisperClose = (): Promise<void> =>
    new Promise((resolve) => {
      this.reconciler.updateContainer(null, this.container, null, resolve);
    });
```
I'm not sure if there is a good way for you to pull the onClose prop off of the ReactElement or not, but if not maybe an easy way to fix this would be to add a second param to renderWhisper which can be set to onCloseHandler , on the render instance, then the render wrapper can do something like..
```
renderInstance.setOnClose(async () => {
   await this.handleWhisperClose();
   renderInstance?.onCloseHandler();
});
```
Or maybe I'm going about this all wrong from my limited exposure to the code

**Comment by iangallOlive** [comment]
Thanks for reporting this! I've created [HELPS-2766](https://crosschx.atlassian.net/browse/HELPS-2776) in our Jira, to track a fix for this.

**Comment by iangallOlive** [comment]
@ssteuteville Sorry, I don't think I meant to close this issue (I think it happened when I merged your PR). Anyways, I just wanted to let you know that we did end up releasing version 3.9.2 earlier, specifically with your changes. Whenever you can, please go ahead and use that in your loop, and let me know if things are fixed for you. 🤞

**Comment by iangallOlive** [comment]
@ssteuteville Great to hear! And no problem!

**Comment by thelunchbox** [comment]
test
