### ISSUE TITLE
Value prop absent from RichTextEditor

### ISSUE THREAD

**Issue by jjnistico** [open-olive/loop-development-kit#478]
Current LDK version: 3.8.1
Current Helps version: 0.29.4
OS: Mac OS 12.1

Use case: I would like to be able to prepopulate a rich text editor box with text pulled from a database.

Issue: There is no value prop for the `RichTextEditor` component like there is for the `TextInput` component.

Current RTE props:
```
onBlur?: (error: Error | undefined) => void;
onChange: WhisperHandlerWithParam<string>;
onFocus?: (error: Error | undefined) => void;
tooltip?: string;
validationError?: string;
```

**Comment by BrettMugglinOlive** [comment]
This should be addressed with release v3.10.0! Let us know if you still have any problems.
