### ISSUE TITLE
href option for Button and Icon

### ISSUE THREAD

**Issue by alokmishra1** [open-olive/loop-development-kit#481]
Please include href option for button and Icon because when we want to open a file using Button and Icon we are bound to use openWithDefaultApplication functionality of filesystem aptitude which is limited to a few file formats. But Link component opens all file types. So if we have href option in Button and Icon then it will be very useful and we will be able to open any file format with click on Button and Icon.

Thanks.

**Comment by JosefBud-olive** [comment]
Hey, @alokmishra1! Thank you for the suggestion! I've created [HELPS-2863](https://crosschx.atlassian.net/browse/HELPS-2863) on our side to track this request. We'll update you here with any updates.

**Comment by MaggieMaSS** [comment]
Thanks for your feedback! This feature has been released on Olive Helps v0.30.2 :)
