### ISSUE TITLE
Enhancement Request: Browser Aptitude - Ability to listen for keyboard input events

### ISSUE THREAD

**Issue by kevinfiol** [open-olive/loop-development-kit#520]
Hey everyone. Great work on the Browser Aptitude!

I'm currently working with it to enhance the experience with an EMR system. One feature that would be nice to have would be to have the ability to subscribe to the user's keyboard input events. Currently, it seems the only way to capture this would be to constantly check and parse the HTML using `sourceHTML`, and see if the user has inputted anything. This would get quite resource intensive if we have to constantly parse the entire page HTML.

**Comment by MaggieMaSS** [comment]
Hey @kevinfiol, from our perspective, you can use keyboard and window aptitudes to achieve that. May I know if there's a reason that you have to listen to keyboard from browser aptitude? :)

**Comment by MaggieMaSS** [comment]
Thanks for your feedback! I have created [HELPS-4135](https://crosschx.atlassian.net/browse/HELPS-4135) to better track this issue!

We'll keep you updated!

**Comment by racary-olive** [comment]
This has been released with the latest release of Olive Helps (`v0.46.2`)
