### ISSUE TITLE
callback not found on whisper close

### ISSUE THREAD

**Issue by rinwa** [open-olive/loop-development-kit#551]
I am getting this error after multiple time update the whisper and then close It

{
  message: "Error invoking remote method 'message-whisperInteraction': callback not found",
  stack: "Error: Error invoking remote method 'message-whisperInteraction': callback not found\n" +
    '    at Function.<anonymous> (file:///C:/Users/Sumit.Rinwa/AppData/Local/olive-helps/app-0.41.5/resources/app/.webpack/renderer/sidebar/index.js:2:1665025)'
}

**Comment by alex-merkert-olive** [comment]
hey @rinwa, thanks for reaching out. I just want to clarify the issue - your loop creates a whisper, updates the whisper a few times, and then you close the whisper and your loop tries to update the whisper again and it's not available, right? That would be expected behavior, as there would be no way to update a whisper after it was closed. Am I understanding this correctly? If you don't mind sharing the steps to reproduce your issue, that would be helpful.

**Comment by rinwa** [comment]
Hi Loop-Development-Team

Steps are as follows.
Step1 - Using loop creates a whisper
Step2 - updates the whisper a few times,
Step3 - then you close the whisper and on close i get the error as
following.

Error occurred in handler for 'message-whisperInteraction': callback not
found
{
  message: "Error invoking remote method 'message-whisperInteraction':
callback not found",
  stack: "Error: Error invoking remote method 'message-whisperInteraction':
callback not found\n" +
    '    at Function.<anonymous>
(file:///C:/Users/Sumit.Rinwa/AppData/Local/olive-helps/app-0.41.5/resources/app/.webpack/renderer/sidebar/index.js:2:1665025)'
}


Sample code  is as following
import { whisper } from ***@***.***/ldk';

export default class ShowResult {
  constructor() {
    this.showwhisper = undefined;
    this.showFlag = 0;
  }

  async showData(compArr) {
    if (this.showFlag == 0) {
      console.log('if testing-------------', this.showFlag);
      whisper
        .create({
          label: 'Search Data',
          onClose: () => {
            this.showFlag = 0;
          },
          components: compArr,
        })
        .then((newWhisper) => {
          this.showwhisper = newWhisper;
          this.showFlag = 1;
          //console.log('if testing-------------', this.showwhisper);
        });
    } else {
      this.showwhisper?.update({
        label: 'Search Data',
        components: compArr,
      });
    }
  }

Regards

**Comment by alex-merkert-olive** [comment]
Thanks for clarifying and adding so much context. I'm curious, where or how is your `showData()` function called? Is it possible that it is being called after the whisper is closed?

**Comment by rinwa** [comment]
With close (Dismiss) icon of the whisper I am closing the whisper. On close get the error and  this.showFlag variable value remain 1 and  onClose: ( )=> { } callback not getting called. if I call the showData() function after the error in log it show like this (Failed to Update Whipser — Whisper Does Not Exist ID for ID) which is fine. but I am getting the error on close the whisper.

**Comment by alex-merkert-olive** [comment]
Would you be able to share all of your source code with us? That may help us reproduce and identify this issue.

**Comment by rinwa** [comment]
showResult.js
import { whisper } from '@oliveai/ldk';

export default class ShowResult {
  constructor() {
    this.showwhisper = undefined;
    this.showFlag = 0;
  }

  async showData(compArr) {
    if (this.showFlag == 0) {
      console.log('if testing-------------', this.showFlag);
      whisper
        .create({
          label: 'Search Data',
          onClose: () => {
            console.log('if testing-------------', this.showwhisper);
            this.showFlag = 0;
          },
          components: compArr,
        })
        .then((newWhisper) => {
          this.showwhisper = newWhisper;
          this.showFlag = 1;
        });
    } else {
      console.log('else testing-------------', this.showwhisper);
      this.showwhisper?.update({
        label: 'Search Data',
        components: compArr,
      });
    }
  }

  close() {
    this.showFlag = 0;
    this.showwhisper.close();
  }

  static onClose(err) {
    this.showFlag = 0;
    if (err) {
      console.error('There was an error closing Intro whisper', err);
    }
    console.log('Intro whisper closed');
  }
}

Index.js
import ShowResult from './showResult';
import { WhisperComponentType } from '@oliveai/ldk/dist/whisper/types';

(async function main() {
  let search = new ShowResult();
  let markdown_new = {
    body: 'Your First Loop page',
    type: WhisperComponentType.Markdown,
  };
  let compArr_New = [markdown_new];
  search.showData(compArr_New);

  let arr = [
    'If you wanted to create the Hello World ',
    'When you click Create Loop, a new VSCode editor will open with your new Loop project',
    'This project contains a pre-generated package.json ',
  ];
  let i = 0;
  var interval = setInterval(function () {
    if (i == 2) {
      clearInterval(interval);
    }
    let markdown = {
      body: arr[i],
      type: WhisperComponentType.Markdown,
    };
    let compArr = [markdown];
    search.showData(compArr);
    i += 1;
  }, 1000);
})();

After all the message shown in the whisper Just close the whisper and check the log you will find the error.

**Comment by alex-merkert-olive** [comment]
Hello @rinwa - I was able to reproduce your issue in the latest version of Olive Helps with the code you provided. I will be entering a bug ticket in our internal system to investigate further. Thanks for you patience!

**Comment by alex-merkert-olive** [comment]
Hello again - I just wanted to update you on this issue. This was indeed a bug with the whisper update process, so we have identified and fixed the issue and it will be released soon. I'll let you know here when that happens. Thanks!

**Comment by rinwa** [comment]
It will be highly appreciated if you could provide release date

**Comment by alex-merkert-olive** [comment]
It should be coming out at the end of this week! Thank you for your patience.

**Comment by racary-olive** [comment]
The fix for this has been released (Olive Helps v0.44.2)

**Comment by rinwa** [comment]
ok thanks, I check
