### ISSUE TITLE
[FEATURE] General query on hosting loop app on Olive App Store

### ISSUE THREAD

**Issue by alokmishra1** [open-olive/loop-development-kit#569]
Hi, We are an Olive partner in developing different loops for some of the clients of Olive. We are currently working on a loop that may require hosting it on Olive App Store in near future.
We require step by step guide for hosting an app in Olive App Store. This guide will be useful in the near future.
Please provide us with any document or a web link. Thanks.

**Comment by iangallOlive** [comment]
Hi! All of our developer documentation is available here: https://oliveai.dev

Our available documentation for publishing a loop in our library is here: https://docs.oliveai.dev/ldk/loop-publication
