### ISSUE TITLE
[BUG]: Browser tab is not opening

### ISSUE THREAD

**Issue by alokmishra1** [open-olive/loop-development-kit#604]
### Describe the bug

We are using Browser aptitude, we have installed the olive plugin. In our application, we are creating a local html file, and giving this html file path and trying to open it in browser. For us it is working fine. But on some users machine browser tab is not opening.
Please help us investigate this issue.

### Steps to Reproduce

[Catherine_ui.main.log](https://github.com/open-olive/loop-development-kit/files/8908009/Catherine_ui.main.log)

I have the log file. Please have a look.

### Olive Helps Version

0.47.4

### LDK Version

Latest

### Operating System

windows

### Code Sample

const FILE_NAME = 'index.html';
    const filePath = await filesystem.join([this.filespath, FILE_NAME]);
    // The permissions we want to give the file, in octal format
    // https://www.linode.com/docs/guides/modify-file-permissions-with-chmod/
    const FILE_PERMISSIONS = 0o777;
    // The write operations to choose from while writing the file
    const { overwrite, append } = filesystem.WriteOperation;

    const writeFileParams = {
      data: FILE_CONTENT,
      path: filePath,
      writeMode: FILE_PERMISSIONS,
      writeOperation: overwrite,
    };
    await filesystem.writeFile(writeFileParams);
    console.log('filePath==========', filePath);
    //const newTabId = await browser.openWindow('file:///' + this.filespath + '/index.html');
    try {
      //const newTabId = await browser.openWindow('file:///' + this.filespath + '/index.html');
      const newTabId = await browser.openTab('file:///' + this.filespath + '/index.html');
      console.log('newTabId============', newTabId);
    } catch (error) {
      const newTabId = await browser.openWindow('file:///' + this.filespath + '/index.html');
      console.log('error newTabId=======', error);
    }

### Code of Conduct

- [X] I agree to these terms

**Comment by racary-olive** [comment]
It looks like there are no registered browser connections. This could either be that the browser extension is not installed or is turned off. I have attached screen shots from the logs.

![image](https://user-images.githubusercontent.com/91288243/173820381-34031453-67a0-499c-8d11-1d0079fde3d3.png)
