### ISSUE TITLE
Bug found in EmitListWhisper()

### ISSUE THREAD

**Issue by advocatia** [open-olive/loop-development-kit#88]
Example Loop path : _loop-development-kit/ldk/csharp/OliveHelpsLDK/Example/Program.cs_

When attempting to run the csharp Example Loop I got this error when calling the EmitListWhisper() function provided by OliveHelps

```
System.ArgumentNullException: Value cannot be null. (Parameter 'value')\r\n   at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)\r\n   at Proto.WhisperListRequest.set_Markdown(String value)\r\n   at OliveHelpsLDK.Whispers.WhisperFormBuilder.BuildRequest(WhisperList list, Session session)\r\n   at OliveHelpsLDK.Whispers.WhisperClient.ListAsync(WhisperList message, CancellationToken cancellationToken)\r\n   at AdvocatiaLoop.Loop.EmitListWhisper() in D:\\Dev\\Saiph\\AdvocatiaLoop\\AdvocatiaLoop\\Program.cs:line 512\r\n   at AdvocatiaLoop.Loop.<SearchbarStream>b__8_0() in D:\\Dev\\Saiph\\AdvocatiaLoop\\AdvocatiaLoop\\Program.cs:line 98
```

This is caused by the WhisperList initialization **not containing a "Markdown" attribute:**

```
private void EmitListWhisper()
  {
      var ccs = new CancellationTokenSource();
      ccs.CancelAfter(5000);
      var whisperList = new WhisperList
      {
          Config = new WhisperConfig {
              Label = "C# Whisper"
          },
          Elements =  new Dictionary<string, ListBase>
          {
              ["Nickname"] = new ListPair {Label="Nickname", Order=1, Value="Old Greg"},
              ["Link"] = new ListLink {Align=ListAlign.Center, Href="https://isitchristmas.com/", Order=2, Text="Is it Christmas?" }
          },
      };       
      _services.Whisper.ListAsync(whisperList, ccs.Token);
      Logger.Info($"Sent List Whisper");
  }
```

It can be fixed by setting the Markdown attribute upon initialization of new WhisperList to a default value.

```
private void EmitListWhisper()
{
    var ccs = new CancellationTokenSource();
    ccs.CancelAfter(5000);
    var whisperList = new WhisperList
    {
        Markdown = "DEFAULT VALUE HERE",
        Config = new WhisperConfig {
            Label = "C# Whisper"
        },
        Elements =  new Dictionary<string, ListBase>
        {
            ["Nickname"] = new ListPair {Label="Nickname", Order=1, Value="Old Greg"},
            ["Link"] = new ListLink {Align=ListAlign.Center, Href="https://isitchristmas.com/", Order=2, Text="Is it Christmas?" }
        },
    };       
    _services.Whisper.ListAsync(whisperList, ccs.Token);
    Logger.Info($"Sent List Whisper");
}
```

**Comment by BrettMugglinOlive** [comment]
This does seem to be an issue with the contract for the ListWhisper in C#, as you shouldn't have to include that Markdown value. This should be addressed though when we release the next major version of the LDK, as the concept of a "ListWhisper" will disappear and be replaced by just a "Whisper", where you can mix an match components from the different types of whispers we have currently.

**Comment by CandiceCLB** [comment]
@BrettMugglinOlive can we confirm that this was resolved with our LDK update?

**Comment by cshields-oliveai** [comment]
@advocatia Given all of the recent work to transition the LDK over to a JavaScript-only model, as @BrettMugglinOlive mentioned, the way that the Whisper Aptitude works has changed.

Please check out the new [`WhisperAptitude` interface](https://open-olive.github.io/loop-development-kit/ldk/javascript/interfaces/whisperaptitude.html). You will be required to be on an LDK version > [3.0.0-beta.1](https://github.com/open-olive/loop-development-kit/releases/tag/v3.0.0-beta.1) to take advantage of this.

We believe that this will resolve your issue, but give this a try and let us know if it's still not behaving the way that you expect.

**Comment by cshields-oliveai** [comment]
@advocatia I am going to close this request out for now, If you are still seeing an issue with the latest release of the LDK, then please feel free to open up a new issue!
